### ISSUE TITLE
[LLC] Host should be URI not string if possible

### ISSUE THREAD

**Issue by chamons** [Azure/autorest.csharp#1136]
I need to research this. Azure.AI.DocumentTranslation has string but the test server tests use uri.

**Comment by chamons** [comment]
Hey @christothes I just checked this out with Azure.AI.DocumentTranslation and i'm seeing string endpoint both in high level and low level. The CodeModel.yaml is the same, so I'm confused.

Can you point me to the swagger you were talking about.

FYI @annelo-msft who's comment originally caused me to file this, in case you have insight.

**Comment by christothes** [comment]
No, you are correct - we do always model as string. I was suggesting that we change that to avoid the pattern of exposing `Uri` on the convenience layer, only to transform it to string for the generated client, and then turn it back into a Uri for the pipeline.

ex.
https://github.com/Azure/azure-sdk-for-net/blob/5a307985a14a3523e765b77c86c01cd44ca8b0d8/sdk/tables/Azure.Data.Tables/src/TableClient.cs#L161
https://github.com/Azure/azure-sdk-for-net/blob/5a307985a14a3523e765b77c86c01cd44ca8b0d8/sdk/tables/Azure.Data.Tables/src/TableClient.cs#L173
```csharp
 var endpointString = connString.TableStorageUri.PrimaryUri.ToString();
...
 _tableOperations = new TableRestClient(_diagnostics, pipeline, endpointString, _version);
```
https://github.com/Azure/azure-sdk-for-net/blob/5a307985a14a3523e765b77c86c01cd44ca8b0d8/sdk/tables/Azure.Data.Tables/src/Generated/TableRestClient.cs#L33
https://github.com/Azure/azure-sdk-for-net/blob/5a307985a14a3523e765b77c86c01cd44ca8b0d8/sdk/tables/Azure.Data.Tables/src/Generated/TableRestClient.cs#L44

```csharp
public TableRestClient(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, string url, string version = "2019-02-02")
{
    ...
    this.url = url;
```

https://github.com/Azure/azure-sdk-for-net/blob/5a307985a14a3523e765b77c86c01cd44ca8b0d8/sdk/tables/Azure.Data.Tables/src/Generated/TableRestClient.cs#L136-L143

```csharp
  internal HttpMessage CreateCreateRequest(TableProperties tableProperties, ResponseFormat? responsePreference, QueryOptions queryOptions)
{
    var message = _pipeline.CreateMessage();
    var request = message.Request;
    request.Method = RequestMethod.Post;
    var uri = new RawRequestUriBuilder();
    uri.AppendRaw(url, false);
    uri.AppendPath("/Tables", false);
    if (queryOptions?.Format != null)
    {
        uri.AppendQuery("$format", queryOptions.Format.Value.ToString(), true);
    }
    request.Uri = uri;
```

For HLCs it's never been much of a concern because the rest client is internal, but the LLC exposes the uri parameter.

**Comment by ellismg** [comment]
FWIW, I think the problem here is because the parameter is not marked as a url in the swagger.  If we take the TableClient [swagger as an example](https://github.com/Azure/azure-rest-api-specs/blob/2df8b07bf9af7c96066ca4dda21b79297307d108/specification/cosmos-db/data-plane/Microsoft.Tables/preview/2019-02-02/table.json#L1713-L1720), we find this:

```json
    "Url": {
      "name": "url",
      "x-ms-parameter-location": "client",
      "description": "The URL of the service account or table that is the target of the desired operation.",
      "required": true,
      "type": "string",
      "in": "path",
      "x-ms-skip-url-encoding": true
    },
```

If you add `"format": "url"` to this, you get the behavior you would expect, I think.  I was able to test this with a transform for TablesClient specifically (see https://gist.github.com/ellismg/2bd267dd362354c2e3512151c3181208 if you want to view the patch) and the generated code looks like it would work as expected.

**Comment by christothes** [comment]
Thanks, @ellismg. Is there a reason you can think of for why args like this *should* be modeled as string?

**Comment by chamons** [comment]
It sounds like this issue can be closed?

**Comment by ellismg** [comment]
> Is there a reason you can think of for why args like this should be modeled as string?

I can't think of one, but I wouldn't take that to mean much.  I do not understand enough about the entirety of the pipeline to know if there are gremlins somewhere.  But this annotation does correctly describe what's going on here so it feels like this should be the correct thing to do.

**Comment by ellismg** [comment]
> Is there a reason you can think of for why args like this should be modeled as string?

BTW, @christothes one reason you might model it as a string is if your template looked more like `{accountName}.service.azure.com/` and you wanted users to just pass in the accountName instead of having to pass in the full URL (which may not be discoverable on the portal, for example).  In practice however, we are trying to take full endpoints which gives us more flexibility (for example, the construction above might not work for a service that can be deployed inside your datacenter since that deployment may not be able to register a DNS entry under azure.com or whatever).
