### ISSUE TITLE
x-accessibility not applying to some generated classes

### ISSUE THREAD

**Issue by heaths** [Azure/autorest.csharp#1163]
While prototyping QnA Maker, I changed `x-accessibility` to `internal` while we focus on a few key scenarios:

````markdown
``` yaml
directive:
  from: swagger-document
  where: $.definitions.*
  transform: >
    $["x-accessibility"] = "internal"
```
````

However, I got a number of errors where a base class was less accessible than a child class. This is in cases like [this](https://github.com/Azure/azure-rest-api-specs/blob/0b9087be79feaca4504b1ecb277875bc6be56617/specification/cognitiveservices/data-plane/QnAMaker/preview/v5.0-preview.2/QnAMaker.json#L812) or [this](https://github.com/Azure/azure-rest-api-specs/blob/0b9087be79feaca4504b1ecb277875bc6be56617/specification/cognitiveservices/data-plane/QnAMaker/preview/v5.0-preview.2/QnAMaker.json#L1744), where properties end up generating a class that is not actually defined as a model.

**Comment by heaths** [comment]
The workaround is to use partial classes to make the generated classes internal. Still, it would be nice if the parent class's accessibility were effectively inheritted.

**Comment by ShivangiReja** [comment]
@heaths `allOf` base class is an anonymous schema which directly defined in the swagger. For example, I've added [this](https://github.com/ShivangiReja/autorest.csharp/blob/Fix_x-accessibility/test/TestProjects/PublicClientCtor/PublicClientCtor.json) swagger where the allOf [base class](https://github.com/ShivangiReja/autorest.csharp/blob/Fix_x-accessibility/test/TestProjects/PublicClientCtor/PublicClientCtor.json#L62-L67) `TestModelDelete` is not directly defined in the swagger, it's an anonymous schema. In order to make this internal you have to add ["x-accessibility": "internal"](https://github.com/ShivangiReja/autorest.csharp/blob/Fix_x-accessibility/test/TestProjects/PublicClientCtor/PublicClientCtor.json#L69) property on the anonymous schema.

**Comment by ShivangiReja** [comment]
@heaths `allOf` child class is an anonymous schema, which is not directly defined in the swagger. For example, I've added [this](https://github.com/ShivangiReja/autorest.csharp/blob/Fix_x-accessibility/test/TestProjects/PublicClientCtor/PublicClientCtor.json) swagger where the allOf [child class](https://github.com/ShivangiReja/autorest.csharp/blob/Fix_x-accessibility/test/TestProjects/PublicClientCtor/PublicClientCtor.json#L62-L67) `TestModelDelete` is not directly defined in the swagger, it's an anonymous schema. In order to make this internal you have to add ["x-accessibility": "internal"](https://github.com/ShivangiReja/autorest.csharp/blob/Fix_x-accessibility/test/TestProjects/PublicClientCtor/PublicClientCtor.json#L69) property on the anonymous schema.

**Comment by ShivangiReja** [comment]
[Here](https://github.com/ShivangiReja/autorest.csharp/blob/Fix_x-accessibility/test/TestProjects/PublicClientCtor/Generated/Models/TestModelDelete.cs#L11) is the generated TestModelDelete class.

**Comment by heaths** [comment]
Looks like a good workaround, but should `x-accessibility` be inherited into child classes generated from anonymous schemas? Seems like something of the parent name is already used as well.

**Comment by timotheeguerin** [comment]
Thing is right now `x-accessibility` is an extension that autorest itself doesn't care, it is just passed through and is something specific to certain generator. Autorest can't just be applying all the extensions to anonymous schema under as it most likely be incorrect for other extensions.

**Comment by ShivangiReja** [comment]
[This](https://github.com/ShivangiReja/autorest.csharp/blob/Fix_x-accessibility/test/TestProjects/PublicClientCtor/Generated/CodeModel.yaml#L180) is an extension that autorest is unaware of, so I don't think we can pass the extension into the child class.

**Comment by heaths** [comment]
@bterlson is this something CADL would handle at least?
