### ISSUE TITLE
[LLC] Arbitrary Client Options Value

### ISSUE THREAD

**Issue by chamons** [Azure/autorest.csharp#1174]
**Describe the issue or request**
There is no way today to create an arbitrary client options pointing to a version we don't know about.

Example:

https://github.com/Azure/autorest.csharp/blob/feature/v3/samples/Azure.AI.DocumentTranslation/Generated/AzureAIDocumentTranslationClientOptions.cs#L28

**Describe your ideas for solutions**
Make Version string virtual so a client could create a derived class and return a custom arbitrary string.

**Comment by annelo-msft** [comment]
Way for ppl to say "I'm using version of API you don't know about" in ServiceVersion enum.
We expect it's a one-line change to make it virtual. => bring estimate down.

**Comment by AlexanderSher** [comment]
Virtual property won't prevent a constructor from throwing an exception.
However, since type is `partial`, user can simply add a new constructor, so I'm not sure if we need to do anything at all:
```cs
    public partial class AzureAIDocumentTranslationClientOptions : ClientOptions
    {
        /// <summary> Initializes new instance of AzureAIDocumentTranslationClientOptions. </summary>
        public AzureAIDocumentTranslationClientOptions(string version)
        {
            Version = version;
        }
    }
```

**Comment by ellismg** [comment]
Since a user picking an API version that the client doesn't know about is a pretty off the beaten path scenario and I worry about adding such an easy way to put you into an invalid state.

Today we generate code that looks like this for ClientOptions for an LLC:

```csharp
namespace Azure.Analytics.Purview.Account
{
    /// <summary> Client options for PurviewAccountClient. </summary>
    public partial class PurviewAccountClientOptions : ClientOptions
    {
        private const ServiceVersion LatestVersion = ServiceVersion.V2019_11_01_preview;

        /// <summary> The version of the service to use. </summary>
        public enum ServiceVersion
        {
            /// <summary> Service version "2019-11-01-preview". </summary>
            V2019_11_01_preview = 1,
        }

        internal string Version { get; }

        /// <summary> Initializes new instance of PurviewAccountClientOptions. </summary>
        public PurviewAccountClientOptions(ServiceVersion version = LatestVersion)
        {
            Version = version switch
            {
                ServiceVersion.V2019_11_01_preview => "2019-11-01-preview",
                _ => throw new NotSupportedException()
            };
        }
    }
}
```

If we make the `Version` property public and virtual (while it remaining read-only):

```csharp
namespace Azure.Analytics.Purview.Account
{
    /// <summary> Client options for PurviewAccountClient. </summary>
    public partial class PurviewAccountClientOptions : ClientOptions
    {
        private const ServiceVersion LatestVersion = ServiceVersion.V2019_11_01_preview;

        /// <summary> The version of the service to use. </summary>
        public enum ServiceVersion
        {
            /// <summary> Service version "2019-11-01-preview". </summary>
            V2019_11_01_preview = 1,
        }

        public virtual string Version { get; }

        protected PurviewAccountClientOptions() { }

        /// <summary> Initializes new instance of PurviewAccountClientOptions. </summary>
        public PurviewAccountClientOptions(ServiceVersion version = LatestVersion)
        {
            Version = version switch
            {
                ServiceVersion.V2019_11_01_preview => "2019-11-01-preview",
                _ => throw new NotSupportedException()
            };
        }
    }
}
```

Then a user could subclass this ClientOptions type and override `Version` to return whatever arbitrary string they wanted to return, but it would be far less likely that you naturally fall into a pit of failure.

I think this is the pattern that @KrzysztofCwalina was imagining.

**Comment by annelo-msft** [comment]
> I worry about adding such an easy way to put you into an invalid state.

@ellismg , isn't @AlexanderSher saying that a customer can add this constructor without subclassing the `<Service>ClientOptions` type?  That does feel like a lighter-weight solution than requiring the subclass.  I don't think @AlexanderSher's approach leads the customer toward the pit of failure, because it's not obvious and it's already possible.  Or are you saying that if the Azure SDK API developer does this this way, the SDK customer could easily throw it into the wrong state?  I see that.  (I sometimes get confused who we're talking about when we say customer because there are so many levels of this.)

Ok, I have convinced myself that @ellismg's is the better approach for the SDK customer (not the SDK author).  Is there any way to prevent the addition of the constructor, or is that something left to API reviews?

**Comment by annelo-msft** [comment]
Postpone this to RC1.1.
