### ISSUE TITLE
[LLC] "Exists" Pattern

### ISSUE THREAD

**Issue by chamons** [Azure/autorest.csharp#1334]
The goal here is to model HEAD operations that are documented as returning 200 or 404 as returning "Response\<bool\>" instead of just "Response", where the bool tells you if you got a 200 or not.

This is a common pattern for exists/check methods.  We already do this (under a configuration knob) for DataPlane clients.

We should probably make this the default behavior for LLC's and then provide opt-outs on a per method basis via an annotation.

**Comment by annelo-msft** [comment]
This is a place that grew-up in WebPubSub
"Is a user in that room?"  Make HEAD request
200 = there (no body returned); 404 = not there
In HLC there's a switch you can use in code generator to make it do response<bool>.

This issue is to implement the ability to do this in LLC -- this is just pulling over the implementation from HLC into LLC.
Should be straightforward - this estimate is fine.

**Comment by AlexanderSher** [comment]
Implementation: https://github.com/Azure/autorest.csharp/blob/b5f9d54b483f0b507d8cf3ac9f48e010fb4c4e64/src/AutoRest.CSharp/Common/Output/Models/RestClientBuilder.cs#L121-L133

**Comment by ShivangiReja** [comment]
I have added a `head-as-boolean` flag for LLC head operations, similar to the Data plane. If the flag is true, then the method returns [`Response<bool>`](https://github.com/Azure/autorest.csharp/blob/feature/v3/test/TestProjects/HeadAsBooleanTrue/Generated/HttpSuccessRestClient.cs#L71), otherwise it returns just the [`Response`](https://github.com/Azure/autorest.csharp/blob/feature/v3/test/TestServerProjects/head/Generated/HttpSuccessRestClient.cs#L64).
 
I’m implementing the same for LLC and below is the generated code for LLC when the `head-as-boolean` flag is true:
 
![image](https://user-images.githubusercontent.com/45216704/134092839-062003b6-2cd7-4094-ac46-28fda668f096.png)

 
 
We don’t return `Response<T>` in LLC today but as a part of this task I added a return type `Response<bool>` when the `head-as-boolean` flag is true. My question is what should we return in ResponseStatusOption.NoThrow case(else condition), when the `head-as-boolean` flag is true? Does the commented code look good to you in else block?

**Comment by ShivangiReja** [comment]
Coping @KrzysztofCwalina's response here:

>This is a good question. 

>I think I would like to see the following behavior called with "no throw" 
>1.	GetRawResponse does not ever throw.
>2.	We still throw when the user accesses the Value property in case the response being an error.
>This might require some modifications to Response<T>

**Comment by ShivangiReja** [comment]
CC: @ellismg, @annelo-msft

**Comment by annelo-msft** [comment]
Created https://github.com/Azure/azure-sdk-for-net/issues/24133 to track the definition of any new APIs for `Response<T>`

**Comment by AlexanderSher** [comment]
What about https://github.com/Azure/azure-sdk-for-net/pull/24122 ?

**Comment by annelo-msft** [comment]
@AlexanderSher -- I don't understand your question - could you clarify?

**Comment by AlexanderSher** [comment]
Your PR adds `IsError` property. With that, do we need to `Response<bool>` in this case at all?

**Comment by AlexanderSher** [comment]
I don't think `IsError` has to be virtual, it can be set in ctor.

**Comment by annelo-msft** [comment]
@ellismg, before we go to far down the path of this new design, can you clarify why we want to return `Response<bool>` instead of `Response`?  Wouldn't we consider the `bool` a model type in the context of LLC?

**Comment by annelo-msft** [comment]
Starting from the premise that once a caller passes a value from `RequestOptions`, they've opted in 100% to LLC and take responsibility for owning the bare `Response`, shouldn't the user be willing to handle the response status directly, e.g.

```csharp
Response existsResponse = client.SomeExistsMethod(...., RequestOptions.NoThrow);
if (!existsResponse.IsError && existsResponse.Status == 200) {
  // the resource exists.
} else if (!existsResponse.IsError && existsResponse.Status == 404) {
  // the resource does not exist.
} else {
  // Response.IsError is `true` so there was a service error.  
  // we can create a new RequestFailedException with the new constructor added with this change: https://github.com/azure/azure-sdk-for-net/issues/24031
}
```

Or have we said we don't want LLC users to use status code?  I'm confused about this middle ground of returning `Response\<T\>` from a protocol method.  We do it in HLC because HLC is all about convenience.  I could see potentially adding this as part of the grow-up story...

**Comment by ellismg** [comment]
> @ellismg, before we go to far down the path of this new design, can you clarify why we want to return Response<bool> instead of Response? Wouldn't we consider the bool a model type in the context of LLC?

> We do it in HLC because HLC is all about convenience. I could see potentially adding this as part of the grow-up story...

You're 100% correct here, Anne.  This is a place where we are sort of bringing models into the picture, except that the "model" is based on the status code of the response instead of the body.

The issue here was a request from @KrzysztofCwalina, who observed this problem in WebPubSub.  In that service, there are a series of "Exists" operations, which in the underlying REST API are just HEAD requests to specific resource paths.  @KrzysztofCwalina actually lead with just returning the `Response` directly, forcing users to check the resulting status code to decide it the object in question existed or not.

In practice, users found this very confusing and so @KrzysztofCwalina did a bit of a grow-up here to return Response<bool> instead.  I think that in practice this is the sort of grow-up that we would do for any of these Exist style methods which are built on top of `HEAD` requests, and so I figured it would be worthwhile it the code-generator could just do this for us.

One thing to consider would be to keep the protocol methods as is and add a "grow-up" version that returns `Response<bool>`, while retaining the protocol method.  I think that's the plan on how we would have done this with the long term grow up story (i.e. if we hadn't caught this before shipping V1) I'm sure why @KrzysztofCwalina decided to change the return type vs adding another overload.

**Comment by KrzysztofCwalina** [comment]
One thing I would add is that I would not "consider the bool a model type". The reason for it is the following: LLC is about removing the least from HLC that we need to be able to achieve LLC goals, i.e. we don't want to remove more than we have to. We have to remove model types that are custom types because they have a non trivial design cost. There is no design cost to bool; it's an existing already designed type.

**Comment by annelo-msft** [comment]
> There is no design cost associated with bools; it's an existing already designed type.

That makes sense, along with Matt's comment that the bool comes from the status code, not the body -- thanks for that clarification!

The other piece I still feel is unresolved is that using `Response<T>` is out of pattern with other LLC methods that all return `Response`.  I know there are strong design principles behind separating the `Response<T>` API from the `Response` API, but I'm not crisp on that thinking ... could we clarify that thinking here so we can think through the implications of using `Response<T>` in a LLC method instead of `Response`?  For example, it feels like with the addition of `IsError` to `Response<T>` for this case, we're starting to add properties to `Response<T>` from `Response`.  Would we continue to do that for any member, or are there times we would not?

**Comment by KrzysztofCwalina** [comment]
We are also not returning just the raw response for LROs, pageables, etc.

**Comment by annelo-msft** [comment]
Do you think it makes sense to add `IsError` to `Response<T>` when it is only relevant to LLC scenarios and that would make it a field on all HLC method return values?

**Comment by annelo-msft** [comment]
Pasting in @KrzysztofCwalina response from elsewhere:

> I feel like turning errors off is a corner scenario. Calling HEAD methods and getting a bool is a mainline scenario. I think we should be optimizing for the mainline scenario, i.e. when users turn errors off, it's OK that there experience is not perfect, i.e. they will have to write:
> 
> Response<bool> result = ...
> if (result.GetRawResponse().Status == x) ...
>

**Comment by annelo-msft** [comment]
So, per @KrzysztofCwalina, we won't add `IsError` to `Response<T>`.  In the normal case, users will write:
```csharp
// This will throw if the service returns an error response
bool exists = client.SomeExistsMethod();
if (exists) {
  // the resource exists.
} else {
  // the resource does not exist.
} 
```

If the user turns off errors, they will need to access the raw response to determine if there was an error:

```csharp
Response<bool> exists = client.SomeExistsMethod(...., RequestOptions.NoThrow);
if (!exists.GetRawResponse().IsError && exists) {
  // the resource exists.
} else if (!exists.GetRawResponse().IsError && !exists) {
  // the resource does not exist.
} else {
  // exists.GetRawResponse().IsError is `true` so there was a service error.  
 // Accessing `exists.Value` will throw an exception.
}
```
