### ISSUE TITLE
[LLC] Generate different ClientOptions for service clients in a package where multiple services version independently

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#1564]
In some SDK packages, multiple service clients are included for services that version independently.  In these cases, we want to generate different ClientOptions types for those services that version independently, so that they can have separate [`ServiceVersion` enums](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-service-version-option).

For example, in Purview, the Purview.Administration package holds clients for Account and MetadataPolicy services, but only one ClientOptions type.  It should generate an AccountClientOptions and a MetadataPolicyClientOptions, which each have versions for those services in the `ServiceVersion` enum.

**Comment by AlexanderSher** [comment]
In CodeModel, versions are applied to the individual operations rather than whole operation groups or collections of operation groups, so we collect them all and take unique values:
```cs
context.CodeModel.OperationGroups
    .SelectMany(g => g.Operations.SelectMany(o => o.ApiVersions))
    .Select(v => v.Version)
    .Distinct()
    .OrderBy(v => v)
    .Select((v, i) => new ApiVersion(ToVersionProperty(v), $"Service version \"{v}\"", i + 1, v))
    .ToArray();
```
To produce one `*ClientOptions` type per client, I've collected api version in every operation group individually. However, there is no way to group them by input file.

**Comment by AlexanderSher** [comment]
One option is to explicitly specify that some client requires individual `*ClientOptions` type, e.g:
```cs
[CodeGenClient(ClientOptions = "SeparateClientOptions")]
public partial class SeparateClient {}
```

**Comment by chunyu3** [comment]
Since CodeModel (modelerfour) lacks of information to identify which batch of clients belong to one clientOptions, other batch belongs to another, Need additional configuration by manual, It is not available to auto generate different clientoptions in codegen.
There is another manual approach: suspress + subclient can achieve this. e.g generate two client options using “SubClient” feature (it is currently in PR: https://github.com/Azure/autorest.csharp/pull/1563):
https://github.com/Azure/azure-sdk-for-net/pull/24828/files

So We will not implement it in codegen now, close this issue.
