### ISSUE TITLE
Missing NuGet package

### ISSUE THREAD

**Issue by aelij** [Azure/autorest.csharp#1573]
**Describe the issue or request**
When using the latest release (`3.0.0-beta.20211013.1`), the corresponding NuGet package cannot be found:

```csproj
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.AutoRest.CSharp" Version="3.0.0-beta.20211013.1" PrivateAssets="All" />
  </ItemGroup>
```

```
error NU1102: Unable to find package Microsoft.Azure.AutoRest.CSharp with version (>= 3.0.0-beta.20211013.1)
error NU1102:   - Found 144 version(s) in https://azuresdkartifacts.blob.core.windows.net/azure-sdk-tools/index.json [ Nearest version: 3.0.0-beta.20210604.3 ]
```

**Comment by collinstevens** [comment]
What is the plan with this package? 

The npm package @autorest/csharp for v3 is a beta package. 

The NuGet package Microsoft.Azure.AutoRest.CSharp is a prerelease package and isn't on the official NuGet feed, but is instead on an Azure specific feed.

I've tried to search for docs/roadmap on GA for use outside of Azure SDK repository, but I can't find any information.

It would be nice to see some information as to when we can expect stable versions of each package as well as an official NuGet package, otherwise, we cannot migrate off of V2.

**Comment by brnbs** [comment]
Any update on this? I still get the same error, and the feed URL in the csproj is still the old one as @weshaggard said

**Comment by foconnor-DS** [comment]
Not only is the generate csproj pointing to the wrong feed, it also apparently requies C# 9.0 or greater, or is some AZURE_NULLABLE constant supposed to be set to false?

**Comment by mhintzke** [comment]
Bumping for visibility..

> I see. @AlexanderSher @ShivangiReja looks like we need to update this feed at https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Common/AutoRest/Plugins/CSharpProj.cs#L49.

@weshaggard Others noted this already, but the `LangVersion` also needs to be bumped to `9.0` or `latest` for the build to work.

**Comment by heinrich-ulbricht** [comment]
Hi there. Just wanted to mention that I was consuming `https://pkgs.dev.azure.com/azure-sdk/public/_packaging/azure-sdk-for-net/nuget/v3/index.json` fine until yesterday, but something in the behavior of that package source changed. I now get lots of 401 errors for regular packages that should've been served by the main Nuget; had to set up a nuget.config to restrict your package source to the one package I consume, directing others to the main Nuget.

**Comment by alston-c** [comment]
@heinrich-ulbricht I've experienced the same problem. I've opened a new issue here: https://github.com/Azure/autorest.csharp/issues/5426
