### ISSUE TITLE
[LLC] Implement LLC generator support for ETag and MatchConditions in LLC APIs

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#1615]
The ETag type can be found in two places in our APIs:

#### As the value of a request header in a conditional request ([RFC7232](https://datatracker.ietf.org/doc/html/rfc7232)) => these translate to method input parameters in LLC

If an operation takes:

- All of If-Match, If-None-Match, If-Modified-Since, and If-Unmodified-Since (this is unusual in MS REST APIs)

The method generated for the operation will take a single [RequestConditions](https://apiview.dev/Assemblies/Review/77bdbcef49a3465fa96fac3fb745bf57#Azure.RequestConditions) type as parameter, allowing each of these values to be set as the appropriate type

- Both of If-Match and If-None-Match

The method generated for the operation will take a single [MatchConditions](https://apiview.dev/Assemblies/Review/77bdbcef49a3465fa96fac3fb745bf57#Azure.MatchConditions) type as a parameter, allowing each value to be set as an [ETag](https://apiview.dev/Assemblies/Review/77bdbcef49a3465fa96fac3fb745bf57#Azure.ETag)

- One of either If-Match or If-None-Match

The corresponding parameter type for the header will be [ETag](https://apiview.dev/Assemblies/Review/77bdbcef49a3465fa96fac3fb745bf57#Azure.ETag)

We have [general guidelines](https://azure.github.io/azure-sdk/general_design.html#conditional-requests) stating that we use friendly boolean values with convenient names indicating the semantics of the operation in our APIs.  These will be added as part of the grow-up story, but not in generated code.

#### In a model body

We don’t generate models for LLC, however, when we generate models for the grow-up story, any field in the model with the name “ETag” (case-insensitive as this varies across REST APIs) will be generated as a property of type ETag, and is the responsibility of the service to validate.

This was designed in this issue: https://github.com/Azure/azure-sdk-for-net/issues/24853

**Comment by chunyu3** [comment]
Hi @annelo-msft 
Current if in the swagger defined If-Match, If-None-Match, If-Modified-Since, and If-Unmodified-Since, LLC codegen will generate method with them as parameter. e.g in AppendBlobClients
 internal HttpMessage CreateCreateRequest(string containerName, string blob, long contentLength, int? timeout, string blobContentType, string blobContentEncoding, string blobContentLanguage, byte[] blobContentMD5, string blobCacheControl, IDictionary<string, string> metadata, string leaseId, string blobContentDisposition, string encryptionKey, string encryptionKeySha256, string encryptionScope, DateTimeOffset? ifModifiedSince, DateTimeOffset? ifUnmodifiedSince, string ifMatch, string ifNoneMatch, string ifTags, string blobTagsString, DateTimeOffset? immutabilityPolicyExpiry, string immutabilityPolicyMode, bool? legalHold)

So this issue want to combine all those 'If-Match, If-None-Match, If-Modified-Since, and If-Unmodified-Since,' header parameters into one model 'RequestConditions', and pass this model as one parameter of the method instead.

**Comment by chunyu3** [comment]
PR: https://github.com/Azure/autorest.csharp/pull/1669
