### ISSUE TITLE
Consider only rename HTTP GET methods with "List" name

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/autorest.csharp#1626]
Right now when we [rename the List operations](https://github.com/Azure/autorest.csharp/blob/5a29781f34d1bfb9d6d4f9050f7bfddaced347f3/src/AutoRest.CSharp/Mgmt/AutoRest/MgmtOutputLibrary.cs#L81), we don't check the corresponding HTTP methods. That could cause a problem that the renamed operation has duplicated name with the other operation under the same API path.

For example, see [`/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DocumentDB/databaseAccounts/{accountName}/readonlykeys`](https://github.com/Azure/azure-rest-api-specs/blob/87c0c6efdace9b67e63c3a7b3a48191048723080/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2021-10-15/cosmos-db.json#L463), it contains two operations:
- `DatabaseAccounts_GetReadOnlyKeys`: HTTP GET
- `DatabaseAccounts_ListReadOnlyKeys`: HTTP POST

So after we rename `DatabaseAccounts_ListReadOnlyKeys`, it will become `DatabaseAccounts_GetReadOnlyKeys` which already exists.

**Comment by archerzz** [comment]
This is better to be done based on Dapeng's request path based generation. When an operation is  not considered as CRUD of a resource (i.e. only an operation), we should use the names from original `operation_id`.

In this case, the two methods generated should be:
- DatabaseAccount.GetReadOnlyKeys()
- DatabaseAccoutn.ListReadOnlyKeys()

Then we won't have naming conflict.

**Comment by archerzz** [comment]
There is .Net SDK guideline requiring to replace `List` with `Get{plural form}`: https://azure.github.io/azure-sdk/dotnet_introduction.html#general-client-standardize-verbs

However, in this case, the two operations **do not** belong to a `Resource`. So:
- If we can ignore that naming rule, then we can fix it by not renaming for non-resource operations.
- Otherwise, use a `rename-operation` is inevitable.

**Comment by archerzz** [comment]
Discussed with Michael on this. An alternative option is just keeping one API. So I contacted `cosmos-db` swagger author Kalyan, and he told me that `Post` should be recommended, since secrets should be passed with `Post`, according to Arm spec.
We can delete `Get` from our SDK. Thus this issue is not a **breaking change** anymore.

This should not be a **breaking change

**Comment by archerzz** [comment]
This part of the https://github.com/azure/azure-sdk-for-net/issues/24694

**Comment by archerzz** [comment]
In the 1st preview of `cosmosdb` track2 mgmt sdk, we've removed `Get` per suggestion from `cosmosdb` team. So we can close this issue.
