### ISSUE TITLE
[feature] support standard checkNameAvailability request

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/autorest.csharp#1651]
The `checkNameAvailability` request has the following pattern:
```
/subscriptions/{subscriptionId}/providers/Microsoft.XXX/checkNameAvailability
```
which accepts a body with model of `name`, `type` and `isFqdn`.

This function will fit perfectly in `Azure.ResourceManager` as a function on the `Subscription`.

This is how a customer would use this function:
```
resp = armClient.GetDefaultSubscription().CheckNameAvailability(
    new ResourceNameAvailabilityRequest{
        Name = "nameToCheck",
        Type = StorageAccount.ResourceType
    }
)
```

**Comment by ArthurMa1978** [comment]
According to #1579, this should be conflicted, so close it

**Comment by m-nash** [comment]
The challenge with this is there is no indication to the customer which ResourceTypes will work.  Our last conversation indicated that a very small percentage of resources support this functionality, but having it here and taking a generic ResourceType makes it look like it will work for all.  I think this would result in a frustrating customer experience since they would have to test each ResourceType one by one to see if they should or shouldn't use this.

Lets discuss in our next sync what our best path forward is.

**Comment by archerzz** [comment]
After discussion, we decided that we won't have a generic check name availability operation in `ResourceManager`. Instead, we will delegate to each RP, and put the methods in the collection classes. See: https://github.com/Azure/autorest.csharp/issues/1821
