### ISSUE TITLE
`SkipModelGeneration` causes compilation errors

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/autorest.csharp#1701]
We have a `SkipModelGeneration` procedure in `MgmtTarget` when the generator sees a model is exactly the same as some model in `Azure.ResourceManager`. But we are not replacing all the reference of that type with the one from Azure.ResourceManager. Therefore we will get a compile error.

**Comment by ArcturusZhang** [comment]
Will be resolved by https://github.com/Azure/autorest.csharp/issues/1629

**Comment by archerzz** [comment]
The original issue is that check name availability definitions are marked as `x-ms-propertyReferenceType`. They cannot be thoroughly replaced when used in cases like method parameters. Changing to `x-ms-typeReferenceType` should resolve this issue.

Or another solution is that we remove them from resource manager, e.g. not trying to replace them in target RPs.

**Comment by archerzz** [comment]
After discussion, we decided to remove check name availability definitions from common types, since we want to delegate check name availability to each RP and there is little value to provide them in common types.

**Comment by archerzz** [comment]
Blocked by internal pipeline error due to test failure, looks like there is a fix for it: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1285658&view=results

remaining work items:

- [ ] build an alpha release of `resourcemanager`
- [ ] bump the version of `resourcemanager` in `autorest.csharp`
- [ ] merge the auto-pr of `autorest.csharp` in `azure-sdk-for-net`
- [ ] remove the unnecessary `no-property-type-replacement` in `deviceupdate` and `cosmosdb`

**Comment by archerzz** [comment]
All items are finished. Closing.
