### ISSUE TITLE
Use the auto-generated version of Managed Identity

### ISSUE THREAD

**Issue by fengzhou-msft** [Azure/autorest.csharp#1727]
When comparing properties in GetExactMatch of ReferenceTypePropertyChooser, we skip the Type property of ResourceIdentity based on the property type being `ResourceIdentityType`, but the swagger of some RPs may have a different name for type (set by `x-ms-enum.name`), then it's not skipped and therefore it cannot be matched.

https://github.com/Azure/autorest.csharp/blob/f018c4eda5c133db025d111f0a877c34acb87fed/src/AutoRest.CSharp/Mgmt/Decorator/ReferenceTypePropertyChooser.cs#L66

Further investigation discovers that we cannot hide the Type property in some cases of update request as the Type should be calculated based on the identity status after updating not based on the identities in the request as the update of managed identity uses [JSON merge patch](https://datatracker.ietf.org/doc/html/rfc7396).

**Comment by ArcturusZhang** [comment]
@fengzhou-msft  I have some concerns on this replacement - we have a type `SystemAssigned, UserAssigned`, and some of the identity types defined in RP directories have the space in it (`SystemAssigned, UserAssigned`) and some do not (`SystemAssigned,UserAssigned`).
Will this replacement break the case with space?

And also I believe we need to make some verification on the enum type instead of not doing verification at all. At least we need to make sure they are "effectively the same", which means they have the same enum values.

**Comment by fengzhou-msft** [comment]
@ArcturusZhang your concern makes sense to me. Let's look at the best way for the match when we work on this issue.

**Comment by ArthurMa1978** [comment]
Can manually fix, so not breaking-change, but should check this for each RP before  GA
