### ISSUE TITLE
Support for OASIS Request Repeatability Headers

### ISSUE THREAD

**Issue by mikekistler** [Azure/autorest.csharp#1950]
**Describe the issue or request**

The Azure API Guidelines say that all operations should be idempotent. This is mainly an issue for POST operations. For situations where a POST needs to be made idempotent, the guidelines recommend

☑️ YOU SHOULD support repeatable requests according as defined in [OASIS Repeatable Requests Version 1.0](https://docs.oasis-open.org/odata/repeatable-requests/v1.0/repeatable-requests-v1.0.html).

Some teams have begun following this advice and including the OASIS Request Repeatability headers in their REST API.

This raises the question of how the Azure SDKs should support OASIS Repeatability headers. 

**Describe your ideas for solutions**

 I think we should treat these headers specially -- meaning _not_ simply expose them as optional parameters that are set by the caller.  Instead, I think the SDK should set these headers within the method for any operation that supports them.

The headers involved are `Repeatability-Request-ID`, which the SDK should set to a freshly minted UUID, and `Repeatability-First-Sent`, which should be set to the current date/time.

The csharp generator should check for the presence of these headers and produce the additional logic as described here.

**Affected Service:**
Batch

**Comment by chunyu3** [comment]
Affect Batch service

**Comment by archerzz** [comment]
Hi @mikekistler could you please elaborate on this statement?
> Instead, I think the SDK should set these headers within the method for any operation that supports them.

C# SDK doesn't provide a Swiss army knife class like `RequestOptions` in Python and Java SDKs. If we don't want to directly expose those OASIS headers in the method signature, then we could:

## Expose them in new option class

- We need the Azure Core team to add a new option class `RepeatableRequestOptions` like [MatchConditions](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/MatchConditions.cs) for `etag` and [RequestConditions](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/RequestConditions.cs) for `if-modified-since`.
- Then in generator, we can generate a method with `RepeatableRequestOptions` when there is OASIS request repeatability headers in the REST API definition.

The problem with this solution is that we still expose something in the method signature.

## Provide an HTTP policy

- We can provide a convenience class `RepeatableRequestHeaderPolicy` which inherits [HttpPipelinePolicy](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Pipeline/HttpPipelinePolicy.cs).
- And users can set those headers like below:
```csharp
var context = new RequestContext();
context.AddPolicy(new RepeatableRequestHeaderPolicy("{Repeatability-Request-ID}", "{Repeatability-First-Sent}"), HttpPipelinePosition.PerCall);

client.PostFoo(...., context);
```

The problem is that:
- It's not straightforward.
- Only protocol methods have `RequestContext` in their singature.

**Comment by lirenhe** [comment]
> Affect Batch service

One correction,  this is likely to be used in the next preview of HealthInsight.

  createJob is LongRunningRpcOperation<OncoPhenotypeData &
                                       **Azure.Core.Traits.SupportsRepeatableRequests,**
                                       OncoPhenotypeResult,
                                       Azure.Core.Traits.SupportsRepeatableRequests &
                                       Azure.Core.Foundations.RetryAfterHeader>;

**Comment by mikekistler** [comment]
> Hi @mikekistler could you please elaborate on this statement?
> > Instead, I think the SDK should set these headers within the method for any operation that supports them.

This is just my suggestion -- the C# architects can decide how to implement this. But my suggestion is that
- There is no parameter or options bag property for the Repeatability-Request-ID or Repeatability-First-Sent header values
- The method creates these values internally and sets them on the request

It seems like a pipeline policy would work well for this but I don't really know the details.

**Comment by archerzz** [comment]
> > Affect Batch service
> 
> One correction, this is likely to be used in the next preview of HealthInsight.
> 
> ```
>   createJob is LongRunningRpcOperation<OncoPhenotypeData &
>                                        Azure.Core.Traits.SupportsRepeatableRequests,
>                                        OncoPhenotypeResult,
>                                        Azure.Core.Traits.SupportsRepeatableRequests &
>                                        Azure.Core.Foundations.RetryAfterHeader>;
> ```

@lirenhe Yes. I noticed it's already in preview version SDK: https://github.com/Azure/azure-sdk-for-net/blob/8f4b156254d9ac26b8de03cf120b5be49e370f0c/sdk/healthinsights/Azure.Health.Insights.CancerProfiling/src/Generated/CancerProfilingClient.cs#L73

> public virtual async Task<Operation<OncoPhenotypeResult>> InferCancerProfileAsync(WaitUntil waitUntil, OncoPhenotypeData oncoPhenotypeData, string repeatabilityRequestId = null, DateTimeOffset? repeatabilityFirstSent = null, CancellationToken cancellationToken = default)

**Comment by lirenhe** [comment]
We already see service teams defining repeatability headers, so we should treat this as high priority.  
cc @m-nash

**Comment by archerzz** [comment]
> > Hi @mikekistler could you please elaborate on this statement?
> > > Instead, I think the SDK should set these headers within the method for any operation that supports them.
> 
> This is just my suggestion -- the C# architects can decide how to implement this. But my suggestion is that
> 
> * There is no parameter or options bag property for the Repeatability-Request-ID or Repeatability-First-Sent header values
> * The method creates these values internally and sets them on the request
> 
> It seems like a pipeline policy would work well for this but I don't really know the details.

Thanks @mikekistler 

Here is current design:
- remove OASIS repeatable headers from method signature
- in SDKs, rest operations will set the header values automatically before sending the first request
  - .NET SDKs by default enable a retry policy which should re-send those headers. If not, we will ask `Azure.Core` team to add one policy for us.
