### ISSUE TITLE
Ability to add a protocol method to a HLC SDK

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.csharp#1970]
There are two approaches:
- Rebase a SDK on top of DPG, which makes new generation add protocol methods natively
- Find a way to generate some methods in protocol mode and expose them

Solution needs to be cost effective, since this is designed to scale fast new methods that don't necessarly requires immediate wrapping with strong design.

**Comment by annelo-msft** [comment]
What we've done is make it possible to configure an OperationId and the generator will add a protocol method for that operation, in an existing HLC SDK.  @lmazuel, we have not addressed your first bullet point.  Is this sufficient, or is this issue asking for us to do both bullet points?

**Comment by ShivangiReja** [comment]
Hi @lmazuel, for this task we will already have HLC SDK generated and we need to generate protocol methods on the top of that. I've some questions about the expectations of this task:
* Do we need to generate public protocol methods or internal protocol methods which will be called by public APIs?
* Do we need to generate all the methods as protocol methods aur just some methods based on the some configuration?

**Comment by lmazuel** [comment]
> What we've done is make it possible to configure an OperationId and the generator will add a protocol method for that operation, in an existing HLC SDK. @lmazuel Laurent Mazuel FTE, we have not addressed your first bullet point. Is this sufficient, or is this issue asking for us to do both bullet points?

One of the two, so we're good :)

> Do we need to generate public protocol methods or internal protocol methods which will be called by public APIs?

Public protocol method, based on some configuration like @annelo-msft just said

> Do we need to generate all the methods as protocol methods aur just some methods based on the some configuration?

This would be unfortunate that in order to expose _one_ method of the Swagger as protocol, we are required to expose all of them. So just some methods based on configuration.

We should aim to a world where we always generate protocol methods:
- Some are internal, because we're HLC-ing them
- Some public as-is
But that's outside of the scope of this issue, and long term vision

**Comment by ShivangiReja** [comment]
Based on @lmazuel's comment we need to generate public protocol methods. For storage we have generated internal protocol methods on RestClient following https://github.com/Azure/autorest.csharp/issues/1970#issuecomment-1063526405 approach. 

@annelo-msft- I've some questions:
* Where should we generate public protocol methods based on the configuration? should we generate public DPGClient and only generate those methods in DPGClient  which are mentioned in the config?
* Should we keep generating internal protocol methods in RestClient for storage?
   *  if we keep generating internal protocol methods in RestClient for storage, then we have to use different config than [protocol-method-list](https://github.com/Azure/autorest.csharp/blob/feature/v3/test/TestProjects/ProtocolMethodsInRestClient/readme.md) otherwise, it will generate internal protocol methods in RestClient as well as public protocol methods for storage.

**Comment by ShivangiReja** [comment]
Based on @lmazuel's comment we need to generate public protocol methods. For storage we have generated internal protocol methods on RestClient following https://github.com/Azure/autorest.csharp/issues/1970#issuecomment-1063526405 approach. 

@annelo-msft - I've some questions:
* Where should we generate public protocol methods based on the configuration? should we generate public DPGClient and only generate those methods in DPGClient  which are mentioned in the config?
* Should we keep generating internal protocol methods in RestClient for storage?
   *  If yes, then we have to use different config than [protocol-method-list](https://github.com/Azure/autorest.csharp/blob/feature/v3/test/TestProjects/ProtocolMethodsInRestClient/readme.md) otherwise, it will generate internal protocol methods in RestClient as well as public protocol methods for storage.

**Comment by annelo-msft** [comment]
Since [only a few non-GA libraries](https://grep.app/search?q=public-clients%3A%20true&filter[repo][0]=Azure/azure-sdk-for-net&filter[path][0]=sdk/) are using `public-clients: true`, we'll postpone doing that part of the work until we have a clear customer need for it.

It is common for hand-written HLC clients to call through to methods on the RestClient.  Since we already have that functionality (to add protocol methods to the inner RestClient), I'll close this issue for now and we can revisit it if we find another approach is needed.
