### ISSUE TITLE
[data-plane] Don't generate optional URIs in client constructors

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2041]
Clients in the [LoadTest API](https://apiview.dev/Assemblies/Review/fe482cb7d6b549ee83b36915d9fcd417) generated constructors with optional endpoints.

We should not allow clients to generate with optional endpoints.  If it is a swagger issue, we should fail generation.

#### Success Criteria

If swagger is missing either `host` or `x-parameterized-host` for a data plane library, generation should fail and notify the operator that this needs to be present in the OpenAPI spec.

**Comment by pshao25** [comment]
I understand the requirement here. Just curious what the load test is and where is its swagger?

**Comment by pshao25** [comment]
Though the API has the optional endpoint, we [initialize ](https://github.com/pshao25/autorest.csharp/blob/9aec4ef9696e3be7f004bc3305a2cef872c62225/test/TestServerProjectsLowLevel/dpg-customization/Generated/DPGClient.cs#L46)the endpoint with the default value provided in [swagger](https://github.com/Azure/autorest.testserver/blob/f6938f4d4d639853f03206e9c2d8bf94abcd7689/swagger/dpg-customization.json#L8) as `endpoint ??= new Uri("http://localhost:3000");` it looks reasonable to me. 


The root cause leading to this appearance is
1. We build endpoint parameter as a [Parameter](https://github.com/Azure/autorest.csharp/blob/f3fa53978ef72f2e96c991cf52667ac6e4cc7a3e/src/AutoRest.CSharp/Common/Output/Models/RestClientBuilder.cs#L586) with `UseDefaultValueInCtorParam` true.
2. When we [write](https://github.com/Azure/autorest.csharp/blob/f3fa53978ef72f2e96c991cf52667ac6e4cc7a3e/src/AutoRest.CSharp/Common/Generation/Writers/CodeWriterExtensions.cs#L194) endpoint parameter, it has default value and its `UseDefaultValueInCtorParam` is true. Then, we added a `= null` to it and initialize it by its default value in constructor body.

**Comment by annelo-msft** [comment]
Here is the Load Test Swagger: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/loadtestservice/data-plane
There was an arch board meeting about the service earlier this week: https://github.com/Azure/azure-sdk/issues/3956

**Comment by pshao25** [comment]
@annelo-msft Thank you!
Could you check my investigation above? We could summarize this into two cases:
1. Swagger has default value with `"host": "localhost:3000"`, example is dpg-customization I mentioned above. The generated constructor makes sense to me.
2. Swagger does not have `host`, example is LoadTest. The generated constructor does looks strange as 
```
public AppComponentClient(AzureKeyCredential credential, Uri endpoint = null, CloudNativeTestClientOptions options = null)
{
    endpoint ??= new Uri("");
}
```
This case we have two options:
2.1 Fix at modelerfour side: 
The generated code model has inappriopriate default value as below. We could remove this line.
![image](https://user-images.githubusercontent.com/97225342/157603895-e963bc06-60c8-4736-bed6-01fe1dcb8e43.png)
2.2 Fix at codegen side (even the root cause lies at modelerfour side):
We could make constructor as 
`public AppComponentClient(AzureKeyCredential credential, Uri endpoint = "", CloudNativeTestClientOptions options = null)`

Please let me your preference.

**Comment by annelo-msft** [comment]
@pshao25, the constructor you suggested would not satisfy [the guidelines for client constructors](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-client-constructor-minimal):
[✅](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-client-constructor-minimal) DO provide a minimal constructor that takes only the parameters required to connect to the service.

```
public AppComponentClient(AzureKeyCredential credential, Uri endpoint = "", CloudNativeTestClientOptions options = null)
```

This does not provide all the information required to connect to the service because no endpoint is specified.

I don't think it makes sense to fix in modelerfour (@AlexanderSher, would that make sense?).  I do think it would make sense for the generator fail and report to the operator that no host is specified, to give them the opportunity to correct the API.  We don't want to generate incorrect APIs silently.

**Comment by pshao25** [comment]
@annelo-msft Thank you for pointing me to the client constructor guideline, then I have to create https://github.com/Azure/autorest.csharp/issues/2055 because our current client does not follow this.

Return back to this issue, if I understand correctly, we have two scenarios:
1. Swagger has host/servers default value: we keep as
```C#
public DPGClient(AzureKeyCredential credential, Uri endpoint = null, DPGClientOptions options = null)
{
    endpoint ??= new Uri("http://localhost:3000");
}
```
2. Swagger has no host/servers field: we make generator fail (So the loadTest should fail).

Could you provide specific example if I'm wrong?

**Comment by annelo-msft** [comment]
Thank you, @pshao25!  Thank you for helping me understand that this is generated based on the value of `host` in the swagger file, or when it is absent.

**1. Swagger has host/servers default value:**

Yes, I think we should leave it the way it is now.

**2. Swagger has no host/servers field:** 

It looks like most data-plane libraries use [x-ms-parameterized-host](https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-parameterized-host) to format the base URL for the request.  If this, or `host` aren't present and there is nothing to specify the base URL, I think it would be helpful to the person generating the library if we let them know that they need to provide one of these values.

@lmazuel -- is this something that the swagger linter should catch, or should we handle it in the generator?

**Comment by annelo-msft** [comment]
Moved the release blocking functionality into: https://github.com/azure/autorest.csharp/issues/2105
This generator warning is a nice to have but not critical for GA.
