### ISSUE TITLE
Client constructor does not follow guideline

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#2055]
Pick any client generated by DPG, e.g., [DGPClient](https://github.com/pshao25/autorest.csharp/blob/9aec4ef9696e3be7f004bc3305a2cef872c62225/test/TestServerProjectsLowLevel/dpg-customization/Generated/DPGClient.cs#L43). It looks like:
```C#
public DPGClient(AzureKeyCredential credential, Uri endpoint = null, DPGClientOptions options = null);
```
According to [the guidelines for client constructors](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-client-constructor-minimal), it should be
```C#
public DPGClient(AzureKeyCredential credential);
public DPGClient(AzureKeyCredential credential, Uri endpoint = null, DPGClientOptions options = null);
```

Same issue in HLC client if it has public constructor, e.g., [PublicClientCtorClient](https://github.com/pshao25/autorest.csharp/blob/e7dfd8b6c5d12803f40c3652c2ac940a91105f22/test/TestProjects/PublicClientCtor/Generated/PublicClientCtorClient.cs#L36) as:
```C#
public PublicClientCtorClient(Uri endpoint, AzureKeyCredential credential, string param1 = "value1", string param2 = null, PublicClientCtorClientOptions options = null)
public PublicClientCtorClient(Uri endpoint, TokenCredential credential, string param1 = "value1", string param2 = null, PublicClientCtorClientOptions options = null)
```

**Comment by annelo-msft** [comment]
@pshao25, thank you for filing this issue!

We should definitely update this in the DPG Generator.  We will want to add the "minimal constructor" to DPG libraries, and when we do, we'll need to make the ClientOptions parameter non-optional to avoid an ambiguous call site.

@ShivangiReja, is the HLC PublicClientCtorClient case @pshao25 has mentioned above something that we use in HLC's today?

**Comment by ShivangiReja** [comment]
>@ShivangiReja, is the HLC PublicClientCtorClient case @pshao25 has mentioned above something that we use in HLC's today?

@annelo-msft - Yes, that is correct but by default we generate only internal constructor in public clients for HLC's because Generator doesn't know which authentication type service supports(Azure Key Credential or AAD) if it isn't mentioned in the swagger or config. We generate public constructors for HLC's, if there is authentication type is defined in the swagger or config like [this](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/anomalydetector/Azure.AI.AnomalyDetector/src/autorest.md).

[Here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/anomalydetector/Azure.AI.AnomalyDetector/src/Generated/AnomalyDetectorClient.cs#L36-L76) is one example of public constructors generated in one of our HLC generated SDK.

**Comment by annelo-msft** [comment]
Thanks, @ShivangiReja!  It looks like AnomalyDetector [hasn't GA'ed yet](https://www.nuget.org/packages/Azure.AI.AnomalyDetector/3.0.0-preview.5), so that API is still in preview.  We may want to file an issue to track this for HLC. 

@pshao25, let's do just the work for the DPG generator for now.  Per offline conversation with Krzysztof, let's generate two constructors for the primary client constructor, where one takes Uri and endpoint, and one takes Uri, endpoint and options, and neither takes default parameters, for example, in [PurviewCatalogClient](https://apiview.dev/Assemblies/Review/bdfd1e265f30435b8bd38e982710ad15#Azure.Analytics.Purview.Catalog.PurviewCatalogClient) we would replace the currently-generated constructor with:

```csharp
public PurviewCatalogClient(Uri endpoint, TokenCredential credential);
public PurviewCatalogClient(Uri endpoint, TokenCredential credential, PurviewCatalogClientOptions options);
```

**Comment by pshao25** [comment]
This [swagger](https://github.com/Azure/autorest.csharp/blob/feature/v3/test/TestProjects/PublicClientCtor/PublicClientCtor.json) will generate constructor like below, same as HLC.
```C#
public PublicClientCtorClient(Uri endpoint, AzureKeyCredential credential, string param1 = "value1", string param2 = null, PublicClientCtorClientOptions options = null)
public PublicClientCtorClient(Uri endpoint, TokenCredential credential, string param1 = "value1", string param2 = null, PublicClientCtorClientOptions options = null)
```

**Comment by annelo-msft** [comment]
@pshao25, the guidelines say:
- [✅](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-client-constructor-minimal) DO provide a minimal constructor that takes only the parameters required to connect to the service.
- [⛔️](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-client-constructor-no-default-params) DO NOT use default parameters in the simplest constructor.
- [✅](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-client-constructor-overloads) DO provide constructor overloads that allow specifying additional options such as credentials, a custom HTTP pipeline, or advanced configuration.

We need to identify which of the PublicClientCtorClient constructors is the main constructor the service team wants customers to use.  For this discussion, let's say this is the TokenCredential constructor.  We will then need to provide:

- Minimal constructor with no default parameters:
```csharp
public PublicClientCtorClient(Uri endpoint, TokenCredential credential)
```
- Overloads that allow specifying additional options, such as:
```csharp 
public PublicClientCtorClient(Uri endpoint, TokenCredential credential, string param1, string param2, PublicClientCtorClientOptions options = null)
public PublicClientCtorClient(Uri endpoint, AzureKeyCredential credential, string param1 = "value1", string param2 = null, PublicClientCtorClientOptions options = null)
```

For the TokenCredential overload, it really depends on the business rules of the service with regard to what the method signatures should be.  Since we can manually add convenience overloads as part of the grow-up story, I would suggest in the case that there are additional parameters to the client constructor, to make them required and the ClientOptions parameter optional, as shown above.

**Comment by pshao25** [comment]
@annelo-msft this still confuses me.
Why
```C#
public PurviewCatalogClient(Uri endpoint, TokenCredential credential, PurviewCatalogClientOptions options = null);
```
changes to a required options as
```C#
public PurviewCatalogClient(Uri endpoint, TokenCredential credential);
public PurviewCatalogClient(Uri endpoint, TokenCredential credential, PurviewCatalogClientOptions options);
```
, while 
```C#
public PublicClientCtorClient(Uri endpoint, TokenCredential credential, string param1 = "value1", string param2 = null, PublicClientCtorClientOptions options = null)
```
changes to an optional options as
```C#
public PublicClientCtorClient(Uri endpoint, TokenCredential credential)
public PublicClientCtorClient(Uri endpoint, TokenCredential credential, string param1, string param2, PublicClientCtorClientOptions options = null)
```
I failed to summarize a rule for this.

What's more, in this case we could not support the call 
```C#
new PublicClientCtorClient(endpoint, credential, param1);
```
any more. Is this OK?

**Comment by annelo-msft** [comment]
> Why is client options optional in the Purview case and not in the test case?

This is because of the following:
- We are required to have a minimal constructor that does not take ClientOptions, e.g. `<service>Client(Uri endpoint, TokenCredential credential)`.  This constructor must not have any default parameters.
- We are required to provide a constructor that lets you specify a custom pipeline, e.g. that takes ClientOptions.
  - If ClientOptions is the only additional parameter for the overload, then we must make it required or we will have ambiguous call site problems.
  - If ClientOptions is not the only additional parameter for the overload, we should not make it required.

So the question becomes, what do we do about the global parameters `param1` and `param2`?

As we discussed offline, what we **should** do with them depends on the business rules of the service.  To make a good decision, we need to understand what `param1` and `param2` mean to the service and when and why a customer would want to provide those values to the service in a constructor.  In all likelihood, it would indicate that the service team should add configuration to introduce subclients.

In order to do something in the auto-generated case, where we don't know the business rules, ideally we would make them all optional, but then we end up again in a case with an ambiguous call site.  I honestly don't have a solution for this that I'm super happy with -- at this point, we need to make a tradeoff.  Rather than providing three additional constructors, I think it makes sense to provide as few as possible (we try to minimize API surface).  Without knowing how to decide which should be optional and which shouldn't based on business rules, I think it's reasonable to make a rule that the global parameters are required and the ClientOptions is not.  Service teams can always add another "grow-up" constructor that implements the correct business rules.

This is also not blocking DPG GA, since we don't have any current DPG service libraries that take global parameters.  I expect we may want to revisit this when we have a DPG client that does to see if this decision works for those real-world cases.

**Comment by annelo-msft** [comment]
Creating a separate issue to officially close on constructor design with global parameters: https://github.com/Azure/autorest.csharp/issues/2106

Determining what to do for PublicClientCtorClient is out of scope for DPG GA.  Moving this to the DPG backlog.
