### ISSUE TITLE
Suppress inner diagnostic scopes in DPG clients

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2069]
Per [this discussion](https://github.com/Azure/azure-sdk-for-net/pull/27363#discussion_r825212261) we want to find a general and efficient solution to suppressing inner diagnostic scopes when HLC clients call through to an inner DPG client.

This issue tracks the work to implement @lmolkova's solution in DPG.

**Comment by pshao25** [comment]
@annelo-msft what would be inner scope looks like? I think we cannot modify it when adding grow-up method right?

**Comment by ShivangiReja** [comment]
If we are create DiagnosticScope in the outer method(grow-up method) as well as in the inner method(DPG generated method)  live tests fail because for some methods we are creating outer and inner scopes with the same name.
For example:
**Outer scope**: [MetricsAdvisorAdministrationClient.CreateDataFeed](https://github.com/ShivangiReja/azure-sdk-for-net/blob/MetricsAdvisor-Experiment/sdk/metricsadvisor/Azure.AI.MetricsAdvisor/src/MetricsAdvisorAdministrationClient.cs#L278)
**Inner scope**: [MetricsAdvisorAdministrationClient.CreateDataFeed](https://github.com/ShivangiReja/azure-sdk-for-net/blob/MetricsAdvisor-Experiment/sdk/metricsadvisor/Azure.AI.MetricsAdvisor/src/Generated/MetricsAdvisorAdministrationClient.cs#L1770)


**Live test failure**:

![image](https://user-images.githubusercontent.com/45216704/158658576-f4e124e4-08c2-410d-b0f7-ce121cdd2eb0.png)



**Live test failure in the pipeline**:
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1436751&view=logs&j=df47e0b9-f7f0-5a6d-001b-395452402a29&t=a918488f-3fbc-5b68-faba-d1917c3f3686&l=581


To workaround this issue I'm removing outer scope created in grow-up method which is handwritten and responsible for serialization and deserialization until we implement @lmolkova's solution in DPG based on [this discussion](https://github.com/Azure/azure-sdk-for-net/pull/27363#discussion_r825212261).

**Comment by annelo-msft** [comment]
Great, thank you @ShivangiReja!  We will want to make sure to put the outer scope back and suppress the inner scope so we can document that this is the correct approach to library authors.

**Comment by annelo-msft** [comment]
> @annelo-msft what would be inner scope looks like? I think we cannot modify it when adding grow-up method right?

@pshao25, as I understand it, we would leave the inner scope the way it is, for example, [here in WebPubSubServiceClient](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/webpubsub/Azure.Messaging.WebPubSub/src/Generated/WebPubSubServiceClient.cs#L63). 

What @ShivangiReja and @lmolkova proposed in [this discussion](https://github.com/Azure/azure-sdk-for-net/pull/27363#discussion_r825212261), was to make a change to one of the following types:
- https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Shared/DiagnosticScopeFactory.cs
- https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Shared/ClientDiagnostics.cs
- https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Shared/DiagnosticScope.cs

**Comment by annelo-msft** [comment]
Once this is complete, can we remove https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Shared/ForwardsClientCallsAttribute.cs ?

**Comment by annelo-msft** [comment]
Closed with https://github.com/Azure/azure-sdk-for-net/pull/28066.  Thanks, @lmolkova!!
