### ISSUE TITLE
Introduce a `Update` method to a resource using the PUT if it does not have a patch

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/autorest.csharp#2141]
This is a convenient method for those resources that do not have a patch, if we do not have this method, we will not have any way to update it inside the resource instance, we have to do it in the collection, which involves its parent.

**Comment by m-nash** [comment]
Today if you have a resource object and it only provides a PUT method and no PATCH which acts as a CreateOrUpdate in order to update it you must do it from the parent since there will be no Update method generated on the resource class.

```
var resource = armClient.GetResource(id);
//this method won't exist
resource.Update(new ResourceData());

//instead customers must do something like this
var parent = armClient.GetParent(id.Parent);
var resourceCollection = parent.GetResources();
resourceCollection.CreateOrUpdate(id.Name, new ResourceData());
```

Since PUT works as a CreateOrUpdate then we should provide a duplicate copy of this method named Update on the resource class directly to avoid the inconvenience above.
