### ISSUE TITLE
Attributes does be set correctly when flat single property model

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/autorest.csharp#2173]
This is reported from Storage team.
The `KeyPolicy` only contain one property, so in the `StorageAccountData` it's flatted with `KeyExpirationPeriodInDays`, but first it becomes **non-nullable** and **read-write** which does not inherit the `KeyPolicy` attribute which is **nullable** and **readonly**.

Swagger is here: https://github.com/Azure/azure-rest-api-specs/blob/71240dcb17f8f66e3d69fae436ee09e7b93aa776/specification/storage/resource-manager/Microsoft.Storage/stable/2021-09-01/storage.json#L3599

**Comment by m-nash** [comment]
The fact that Expiration has a get and a set is actually correct however as I was doing my testing around this I realized that in some cases where the outer property is Readonly and the Inner property is not we run into a potential null reference issue.

To address the original concern if we did not wrap this code would be valid
```csharp
var data = GetStorageAccountFromAzure();
if (data.KeyPolicy is not null)
{
    var oldValue = data.KeyPolicy.KeyExpirationPeriodInDays;
    var newValue = oldValue + 1;
    data.KeyPolicy.KeyExpirationPeriodInDays = newValue;
}
```
However you cannot "create" a KeyPolicy on this data object its only returned from the service.

When we wrap the exact same behavior just without the extra layer in objects
```csharp
var data = GetStorageAccountFromAzure();

var oldValue = data.KeyExpirationPeriodInDays;
var newValue = oldValue + 1;
data.KeyExpirationPeriodInDays = newValue;
```

The difference is there is no way to check if KeyPolicy was null and if it was then `data.KeyExpirationPeriodInDays` will result in a null reference exception.

I see two options in this case

### We don't flatten when the outer property is readonly and the inner property is not.
This will result in roughly 30ish properties not being wrapped 2 of which are in the GA library Azure.ResourceManager.Resources which we can manage with EB never.  We can shrink this a bit by further looking at whether or not the object can be constructed with a null and if not then it would still be safe to flatten.

### We add explicit exceptions to the setter and make the getter nullable
In the case of StorageAccountData and KeyPolicy it goes from
```csharp
        public int KeyExpirationPeriodInDays
        {
            get => KeyPolicy.KeyExpirationPeriodInDays;
            set => KeyPolicy.KeyExpirationPeriodInDays = value;
        }
```
to
```csharp
        public int? KeyExpirationPeriodInDays
        {
            get => KeyPolicy?.KeyExpirationPeriodInDays;
            set
            {
                if (KeyPolicy is null)
                    throw new InvalidOperationException("There is no KeyPolicy set for this StorageAccount");
                if (!value.HasValue)
                    throw new ArgumentNullException(nameof(value), "KeyExpirationPeriodInDays cannot be null");
                KeyPolicy.KeyExpirationPeriodInDays = value.Value;
            }
        }
```
The property type becomes nullable allowing us to return null if KeyPolicy is null.  The setter needs to provide valid errors in the cases where KeyPolicy is null instead of the current NullReferenceException
