### ISSUE TITLE
Add comment that uniquely identifies DPG Clients

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2195]
We have a need to be able to search through the azure-sdk-for-net code base and identify which clients are generated by DPG.

**Comment by archerzz** [comment]
We already generate a `/// <summary>....` comment for each DPG client class. I think we just need to update its contents so that a DPG client can be easily identified.

The content of `<summary>` is from `LowLevelClient.Description` which is determined in https://github.com/Azure/autorest.csharp/blob/a7ae775b4ef1592532b075e6baada85ebc7431cf/src/AutoRest.CSharp/LowLevel/Output/LowLevelClient.cs#L54-L56

I think we could change the logic to:

```csharp
Description = BuilderHelpers.EscapeXmlDescription(string.IsNullOrWhiteSpace(description)
        ? $"Data plane generated client for {ClientBuilder.GetClientPrefix(Declaration.Name, context)}."
        : $"Data plane generated client. {BuilderHelpers.EscapeXmlDescription(description)}");
```

**Comment by annelo-msft** [comment]
That sounds great, @archerzz.  I'd love to see what this looks like when we run it on the azure-sdk-for-net repo so we can see if there are any special cases we'd need to consider.  Thanks!

**Comment by archerzz** [comment]
@annelo-msft Here is the PR on `autorest.csharp`: https://github.com/Azure/autorest.csharp/pull/2269

And this is the PR on `azure-sdk-for-net`: https://github.com/Azure/azure-sdk-for-net/pull/29041

**Comment by lirenhe** [comment]
@annelo-msft and @archerzz,  can this information also be included in the readme.md?   This could the centralized place we could query and check.

**Comment by archerzz** [comment]
@lirenhe Current we don't generate `readme.md`.

**Comment by lirenhe** [comment]
> @lirenhe Current we don't generate `readme.md`.

I understand that, in the PS script for DPG project generation, can we add one additional step to put this info into readme file
