### ISSUE TITLE
Make RequestContext required on protocol methods in the event of an ambiguous call site with grow-up method

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2204]
When we are growing up an DPG client into a Convenience Client, we have two different cases:

1. The protocol client API has GA'ed, so we can't change the protocol methods (this will be the case for most new libraries)
2. The convenience client API has GA'ed, so we can't change the convenience methods (this will be the case for many existing HLC libraries)

We have documented the process for 1, growing up protocol methods, at https://github.com/Azure/azure-sdk-for-net/blob/main/doc/DataPlaneCodeGeneration/DeveloperDrivenEvolution.md.

For the second case, if we have a method with an ambiguous call site, we will [disambiguate the methods signatures by making RequestContext and other parameters required](https://github.com/Azure/azure-sdk-for-net/issues/28123#issuecomment-1106838980).

The generator will need to be updated to detect this case and generate the protocol method in the appropriate way.

**Comment by archerzz** [comment]
## Design

- Add a `decorator`, like what mgmt plane does, which will traverse all protocol method and search any existing convenience method that is ambiguous. If such a method is found, we change the signature of the corresponding protocol method to make all parameters as required.
- We can search the existing convenience methods from `SourceInputModel`.
- Search Criteria:
  - The method has the same name
  - The method has the same number of required parameters
  - Each parameter is either:
    - the same type
    - or can be implicitly converted
  - **[Exception]**: If a method with exactly the same signature is found, return false since that means customers have composed a customization of protocol method. And we'll let them take the responsibility of ambiguity.

**Comment by annelo-msft** [comment]
@ShivangiReja FYI

**Comment by archerzz** [comment]
For ambiguity, I found there could be more cases than we thought. We need to decide which cases we should detect.

## Potential Ambiguous Cases

### Case 1: Same Types Of Parameters

```csharp
public class Program
{
	public static void Main()
	{
		foo(16); // Compilation error
	}
	
	// OLD
	private static void foo(int a, string content = null)
	{
		Console.WriteLine("This is double {a}");
	}
	
	// NEW
	private static void foo(int b, Options options = null)
	{
		Console.WriteLine("This is int {a}");
	}
}
```

### Case 2: New Parameter Is A Parent Class

```csharp
public class Program
{
	public static void Main()
	{
                foo(new ()B); // No compilation error, but method to invoke is actually changed
	}
	
	// OLD
        private static void Foo(A a)
	{
		Console.WriteLine("This is A");
	}
	
        // NEW
	private static void Foo(B b)
	{
		Console.WriteLine("This is B");
	}
}

public class A
{
}

public class B: A
{
}
```

### Case 3: New Parameter Can Be Implicitly Converted to Old Parameter

```csharp
public class Program
{
	public static void Main()
	{
		foo(16); // No compilation error, but method to invoke is actually changed
	}
	
	// OLD
	private static void foo(double a)
	{
		Console.WriteLine("This is double {a}");
	}
	
	// NEW
	private static void foo(int b)
	{
		Console.WriteLine("This is int {a}");
	}
}
```

### Case 4: New Parameter Also Has Same Implicit Conversion Operator

```csharp
public class Program
{
	public static void Main()
	{
		foo("abc"); // Compilation Error!
	}
	
        // OLD
	private static void foo(A a)
	{
		Console.WriteLine("This is IA");
	}
	
        // NEW
	private static void foo(B b)
	{
		Console.WriteLine("This is IB");
	}
}

public class A
{
	private string content;
	
	public A(string c)
	{
		content = c;
	}
	
    public static implicit operator A(string str)
	{
	    return new A(str);
	}
}

public class B
{
	private string content;
	
	public B(string c)
	{
		content = c;
	}
	
    public static implicit operator B(string str)
	{
		return new B(str);
	}
}
```

## Thoughts

- We should detect case 1.
- Case 2&3 are valid, and we should **not** detect them, because:
  - There won't be compilation error.
  - New method provides more specific matching, which is the purpose of overloading.
  - If the new method expects to accept a different parameter, I think there might be some smell in the original API design, and we'd better let developers to resolve it manually (e.g. provide their own implementation).
- We should detect case 4, but it requires a lot of work (we need to move the analysis of both generated codes and source input into Roslyn and write an algorithm to detect the intersection of implicit conversion). Case 4 is possible but maybe not probable in reality. So we could postpone this to later release.

**Comment by pshao25** [comment]
Let me put it in a DPG way:
Case 1:
```C#
// protocol
private static void case1(int a, RequestContext requestContext = null)
{
}

// HLC
private static void case1(int a, CancellationToken cancellationToken = default)
{
}

case1(16); // Ambiguous call
```
Case 2:
```C#
class Model : RequestContent
{
}

// protocol
private static void case2(RequestContent requestContent, RequestContext requestContext = null)
{
}

// HLC
private static void case2(Model model, CancellationToken cancellationToken = default)
{
}

case2(new Model()); // Looks good to me
```
Case 4:
```C#
class Model
{
    public static implicit operator Model(BinaryData content)
    {
        return new Model();
    }
}

// protocol
private static void case4(RequestContent requestContent, RequestContext requestContext = null)
{
}

// HLC
private static void case4(Model model, CancellationToken cancellationToken = default)
{
}

case4(BinaryData.FromString("a")); // Ambiguous call, because our RequestContent also has same implicit casting
```

**Comment by annelo-msft** [comment]
We are postponing this issue because making `RequestContext` required will not work in cases where the method takes an optional parameter.  To my knowledge, we don't want to make an optional parameter required just because of an ambiguous call site.  It's possible we'll change this decision later, but we'll postpone redesign for now.

Marking non-blocking for v1.0 GA because, per @lmazuel 

We're not clear exactly how we want to solve this issue, but we can solve it manually for now, by disabling the generation of the problematic method and decide manually what to do. And this is assuming we have both a HLC scenario, and conflict.

Let's consider this non-blocking for GA, backlog, and **put it in 1.2**.  If we run into this problem before 1.2 for a service, let's use that as a brainstorm example to confirm what we want.

**Comment by annelo-msft** [comment]
@lirenhe, could you help put this in v1.2?  I'm not sure which project/milestone that should be.

**Comment by lirenhe** [comment]
> @lirenhe, could you help put this in v1.2? I'm not sure which project/milestone that should be.

Label added.
