### ISSUE TITLE
BinaryData returned from some Pageable<BinaryData> does not contain valid JSON

### ISSUE THREAD

**Issue by KrzysztofCwalina** [Azure/autorest.csharp#2244]
It seems like we are stripping quotes from JSON strings:
https://github.com/Azure/autorest.csharp/blob/feature/v3/src/assets/Generator.Shared/LowLevelPageableHelpers.cs#L82

This means that the resulting BinaryData instances won't be parsable with JSON parsers, unlike any other BinaryData instances returned from DPG APIs.

I think we should guarantee that if response content type is application/json, all BinaryData instances returned from corresponding DPG methods can be parsed using 

``` 
BinaryData data = ...
var parsed = JsonDocument.Parse(data.ToMemory());
```

**Comment by annelo-msft** [comment]
> It seems like we are stripping quotes from JSON strings:

In fact, with this line, we are increasing the width of the content to *include* the quotes.  This is because because for tokens of type JsonTokenType.String, the token includes the quotes containing the string value, e.g. `<TokenStartIndex>"hello"<TokenEndIndex>`, whereas the `ValueSpan` property contains only the string value, e.g. `"<ValueSpanStartIndex>hello<ValueSpanEndIndex>"`

We need to:
- [ ] Update the LowLevelPageableHelpers.cs file as shown in https://github.com/Azure/autorest.csharp/pull/2249
- [ ] Add autorest.testserver tests containing a paging method that returns string items, not object items.
- [ ] Add tests to `PagingTests` to test this new case.  Removal of the line in question should cause the tests to fail.

.
See https://docs.microsoft.com/en-us/dotnet/api/system.text.json.utf8jsonreader.tokenstartindex?view=net-6.0#remarks

**Comment by pshao25** [comment]
@annelo-msft could you help me understand what this issue is? I didn't see any problem with string, and the fix in your PR is only comment related.

**Comment by annelo-msft** [comment]
We need to add a comment to explain why the code is written this way, and refactor the code for clarity.
We need to add tests to validate that this functionality is correct to prevent regressions, as there are not currently any tests that cover this scenario - all testing was done for this in a private project that isn't under source control.

**Comment by pshao25** [comment]
So actually there is no code defect. What we need to do is to add test, right?

> Removal of the line in question should cause the tests to fail.

Which line are you refering to?

**Comment by annelo-msft** [comment]
> So actually there is no code defect. What we need to do is to add test, right?

That is correct.

> Which line are you refering to?

[Line 82](https://github.com/Azure/autorest.csharp/pull/2249/files#diff-da3d2e36a2a2abafda9d3b07fe3bdd52564ca64f6bb1699fc1b4f25073e5fb24L82) in the original file.

**Comment by pshao25** [comment]
We don't have this file and logic. So close.
