### ISSUE TITLE
Handle WaitForCompletionResponse scope in the Grow-up story

### ISSUE THREAD

**Issue by pshao25** [Azure/autorest.csharp#2297]
**Backgroud:**
To resolve https://github.com/Azure/autorest.csharp/issues/2236, we agree to add the scope `WaitForCompletionResponse` to `OperationInternal`/`OperationInternalOfT`, since DPG, Mgmt, HLC, grow-up from DPG all need this.

**Current behavior:** 
Only grow-up from DPG scnario has `WaitForCompletionResponse` scope because we implemented this wrapper at https://github.com/Azure/autorest.csharp/blob/12cb9bee234b546de6795a95328f1da7dd80acf6/src/assets/Generator.Shared/LowLevelOperationHelpers.cs#L143

**Solution to #2236:** 
Will add the `WaitForCompletionResponse` scope in https://github.com/Azure/azure-sdk-for-net/pull/29033

**Follow-up question: Do we need to remove the [scope wrapper](https://github.com/Azure/autorest.csharp/blob/12cb9bee234b546de6795a95328f1da7dd80acf6/src/assets/Generator.Shared/LowLevelOperationHelpers.cs#L143) in grow-up scenario?**
It is straightforward to remove this, but the problem is:
In grow-up LRO we created a new scope [DPGClient.LroValue](https://github.com/Azure/autorest.csharp/blob/12cb9bee234b546de6795a95328f1da7dd80acf6/test/TestServerProjectsLowLevel/dpg-customization/Customization/DPGClient.cs#L99) expecting we will have a scope named `DPGClient.LroValue.WaitForCompletionResponse`. But we call DPG method inside grow-up method [here](https://github.com/Azure/autorest.csharp/blob/12cb9bee234b546de6795a95328f1da7dd80acf6/test/TestServerProjectsLowLevel/dpg-customization/Customization/DPGClient.cs#L103). During the call to DPG method, we open a scope named `DPGClient.Lro` and pass this name to the procedure of creating the `LowLevelFuncOperation`,
https://github.com/Azure/autorest.csharp/blob/12cb9bee234b546de6795a95328f1da7dd80acf6/test/TestServerProjectsLowLevel/dpg-customization/Generated/DPGClient.cs#L301
which will pass to the constructor of `OperationInternal`
https://github.com/Azure/autorest.csharp/blob/12cb9bee234b546de6795a95328f1da7dd80acf6/src/assets/Generator.Shared/LowLevelFuncOperation.cs#L19-L24
and then stored in a private string of `OperationInternalBase` at https://github.com/Azure/azure-sdk-for-net/blob/96b69bb0a936cb599d1e1c28d25f8bd63ebd4a77/sdk/core/Azure.Core/src/Shared/OperationInternalBase.cs#L36
Then, when we call the `WaitForCompletion` and creates the scope for this, it will use the scope name of the previous stored value, i.e., `DPGClient.Lro` insread of `DPGClient.LroValue`,
https://github.com/Azure/azure-sdk-for-net/blob/96b69bb0a936cb599d1e1c28d25f8bd63ebd4a77/sdk/core/Azure.Core/src/Shared/OperationInternalBase.cs#L192

**Solution to this issue:**
1. Don't remove the scope wrapper in grow-up. https://github.com/Azure/autorest.csharp/pull/2290
2. Remove the scope wrapper in grow-up but add a method to `OperationInternalBase` to changeg the scope name. https://github.com/Azure/autorest.csharp/pull/2298. Something like https://github.com/Azure/autorest.csharp/blob/0a4fbbb8567235bcf21970dc294a46a42634687b/src/assets/Azure.Core.Shared/OperationInternalBase.cs#L228

**Comment by annelo-msft** [comment]
> Only grow-up from DPG scnario has WaitForCompletionResponse scope because we implemented this wrapper at

I don't think this is true.  WaitForCompletionResponse is on both Operation and Operation\<T\>, so a customer could call these public methods and we would need to open a scope with this name.

> Do we need to remove the [scope wrapper](https://github.com/Azure/autorest.csharp/blob/12cb9bee234b546de6795a95328f1da7dd80acf6/src/assets/Generator.Shared/LowLevelOperationHelpers.cs#L143) in grow-up scenario?

I don't understand why we would need to do this.    How is this different from the case you are documenting in [this PR](https://github.com/Azure/azure-sdk-for-net/pull/28947/files#diff-a7e2ed847aaef440657de71ae505b5df58ac47725b3b6a92ae28e8d6679f6aa7R115)?


In order to determine if this issue should block GA, I will need you to provide a repro.  Can you please provide:
1. What steps should be taken to produce the error?
2. The actual result
3. The expected result

My understanding is that @AlexanderSher implemented the required functionality to correctly enable diagnostic scopes for grow-up methods in https://github.com/Azure/autorest.csharp/pull/2211.  If the functionality he implemented is not correct, we should add a test and show that it fails.  We should then make the change needed to make the test succeed.

**Comment by pshao25** [comment]
Let me put it in this way.

Let's switch off the suppression feature by not passing the `true` to the DPGCilent client like:
``` C#
public DPGClient(AzureKeyCredential credential, Uri endpoint, DPGClientOptions options)
{
    ...
    ClientDiagnostics = new ClientDiagnostics(options); // not passing true
    ...
}
```
So that we could see the scopes during LRO grow-up scenario when they are not suppressed.
**Actual behavior:**
![image](https://user-images.githubusercontent.com/97225342/173012391-294bcff4-6054-4fe9-9e9f-725a518679c6.png)
Pay attention to `Scopes[1]`, it is `DPGClient.Lro`. And `Scopes[0]` and `Scopes[2]` start with `DPGClient.LroValue`.

I think expected behavior should not have `DPGClient.Lro` between two `DPGClient.LroValue`s.

**Comment by annelo-msft** [comment]
Thank you @pshao25, this is a very helpful explanation!

> I think expected behavior should not have DPGClient.Lro between two DPGClient.LroValues.

It would be good to check, but my expectation is that:
- `DPGClient.LroValue` and `DPGClient.Lro` are created when the StartOperation method is called, as described in https://github.com/Azure/autorest.csharp/issues/2136#issuecomment-1092257699
- `DPGClient.LroValue.WaitForCompletionResponse` and following spans are created when `Operation.WaitForCompletionResponse` is called.

Could you confirm that this is the case?

If so, given this, if nesting scope suppression was turned on, the spans would look like what's described in https://github.com/Azure/autorest.csharp/issues/2136#issuecomment-1092257699

Since this is only a problem when nested scope suppression is disabled in DPG clients, and this would require the library developer to manually override [ClientDiagnostics creation in generated code](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/deviceupdate/Azure.IoT.DeviceUpdate/src/Generated/DeviceUpdateClient.cs#L62) and is not settable by end-user customers, I think it's ok to not block GA on this.  (Architects would discourage doing this because it would create a library that doesn't follow the guidelines.)

I've created https://github.com/Azure/azure-sdk-for-net/issues/29215 to track adding test coverage for this issue.

**Comment by pshao25** [comment]
Thank you @annelo-msft !
Sorry I didn't pointed out the scenario I tested. Yes, the scenario is we start a new operation with `WaitUntil.Started`. It aligns to https://github.com/Azure/autorest.csharp/issues/2136#issuecomment-1092257699 with nested scope suppression off. And I tested the scenario with `WaitUntil.Completed`, it aligns too.

> Even if it were a problem, if would only be an issue when nested scope suppression is disabled in DPG clients, and this would require the library developer to manually override [ClientDiagnostics creation in generated code](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/deviceupdate/Azure.IoT.DeviceUpdate/src/Generated/DeviceUpdateClient.cs#L62) and is not settable by end-user customers. (And architects would discourage doing this because it would create a library that doesn't follow the guidelines.)

The example you provided doesn't have `<PackageReference Include="System.Diagnostics.DiagnosticSource" Version="5.0.0"/>`. The scope will not be suppressed if user is not on .net 5.0. Are we going to add this?

**Comment by pshao25** [comment]
The suppressed behavior is the same as https://github.com/Azure/autorest.csharp/issues/2136#issuecomment-1092257699
The none-suppressed behavior will be tracked in https://github.com/Azure/azure-sdk-for-net/issues/29215
