### ISSUE TITLE
Run codegen over azure-sdk-for-net repo as part of PR validation step

### ISSUE THREAD

**Issue by AlexanderSher** [Azure/autorest.csharp#2300]
Currently, if autorest.csharp update has issues when used in azure-sdk-for-net, autorest.csharp CI pipeline got blocked. To minimize the change of this, we can try to run codegen on top of azure-sdk-for-net during PR. At the same time, PR owner should be able to make necessary updates in azure-sdk-for-net before PR is merged.

So the following update to autorest.csharp `build.yml` is proposed:
- For the `pr` trigger, use PR number (instead of date) to create and publish a test-only nuget package
- Add a step that would create a draft PR in azure-sdk-for-net
- Update that PR in azure-sdk-for-net every time PR in autorest.csharp is updated until all changes have passed.
- In release build, update PR in azure-sdk-for-net (instead of creating a new one) with released package and make PR ready for review

**Comment by hallipr** [comment]
I'm partially addressing this request with #3378.

Rather than publish a nuget package and create a PR in azure-sdk-for-net in the middle of a PR for autorest.csharp, we can just do the azure-sdk-for-net builds in the autorest.csharp pipeline run.   This will allow us to gen, build, and optionally test the azure-sdk-for-net clients without creating any artifacts outside of the pipeline run.

**Comment by chunyu3** [comment]
already in pipeline. close this.
