### ISSUE TITLE
Generate models with read-only properties from Cadl

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2341]
### Input/Output/Round-trip models with read-only properties
This issue tracks the work to implement generation of models with read-only properties in the DPG generator.

Input models are not addressed, because if a model is input-only, it should not have any read-only properties.

If we need to triage this work, generation of Round-trip models is P0, and generation of Output models is P1.

#### Overview

Read-only properties are indicated via the `@visibility("read")` decorator in Cadl, see https://github.com/microsoft/cadl/blob/main/docs/tutorial.md#visibility-decorators.

#### Input Cadl file
[Cadl testserver models/readonly-properties](https://github.com/Azure/cadl-ranch/tree/main/packages/cadl-ranch-specs/http/models/readonly-properties)

#### Expected output

OutputModel files:
- [x] [OutputModel.cs](https://github.com/annelo-msft/azure-sdk-for-net/blob/cadl-model-readonly-property/sdk/template/Azure.Template/src/Generated/Models/OutputModel.cs)
- [x] [OutputModel.Serialization.cs](https://github.com/annelo-msft/azure-sdk-for-net/blob/cadl-model-readonly-property/sdk/template/Azure.Template/src/Generated/Models/OutputModel.Serialization.cs)
- [x] Output model has no initialization constructor, unless it contains collection properties. Collection properties are initialized in an internal initialization constructor. (See discussion below in https://github.com/Azure/autorest.csharp/issues/2341#issuecomment-1220387199)
- [x] Output model has serialization constructor that takes all property values
- [x] Readonly properties are get-only
- [x] Readonly model properties are get-only
- [x] Readonly collection properties are IReadOnlyLists
- [x] DeserializeOutputModel method is defined in serialization partial class
- [x] Readonly properties are deserialized

RoundTripModel files:
- [x] [RoundTripModel.cs](https://github.com/annelo-msft/azure-sdk-for-net/blob/cadl-model-readonly-property/sdk/template/Azure.Template/src/Generated/Models/RoundTripModel.cs)
- [x] [RoundTripModel.Serialization.cs](https://github.com/annelo-msft/azure-sdk-for-net/blob/cadl-model-readonly-property/sdk/template/Azure.Template/src/Generated/Models/RoundTripModel.Serialization.cs)
- [x] Round-trip model initialization constructor does not take read-only property values
- [x] Round-trip model initialization constructor initialized read-only collection properties to ReadOnlyList
- [x] Round-trip model has serialization constructor that takes all property values
- [x] Readonly properties are get-only
- [x] Readonly model properties are get-only
- [x] Readonly collection properties are IReadOnlyLists
- [x] Write operation is defined in serialization partial class
- [x] Readonly properties are NOT serialized
- [x] DeserializeOutputModel method is defined in serialization partial class
- [x] Readonly properties are deserialized

ReadonlyModel files:
- [ ] [ReadonlyModel.cs](https://github.com/annelo-msft/azure-sdk-for-net/blob/cadl-model-readonly-property/sdk/template/Azure.Template/src/Generated/Models/ReadonlyModel.cs)
- [ ] [ReadonlyModel.Serialization.cs](https://github.com/annelo-msft/azure-sdk-for-net/blob/cadl-model-readonly-property/sdk/template/Azure.Template/src/Generated/Models/ReadonlyModel.Serialization.cs)
- [ ] ReadonlyModel is generated as an output-only model

**Comment by annelo-msft** [comment]
Note regarding overloading of the term read-only ... sometimes we mean it in the context of the service API definition (e.g. `@visibility("read")`), and sometimes we mean it in terms of the .NET property (e.g. the property doesn't have a setter).

**Comment by archerzz** [comment]
@annelo-msft I have some suggestion on the generated codes:

1. We probably don't need `.AsReadOnly()` [when initializing `IReadOnlyList` in public constructor](https://github.com/annelo-msft/azure-sdk-for-net/blob/32070b548d53531ba3c751888a8b3719941a1945/sdk/template/Azure.Template/src/Generated/Models/RoundTripModel.cs#L18), because the corresponding field is `IReadOnlyList`:
`            RequiredReadonlyStringList = new List<string>(0).AsReadOnly();`
2. I think we should have null check for required reference types [in the serialization constructor](https://github.com/annelo-msft/azure-sdk-for-net/blob/32070b548d53531ba3c751888a8b3719941a1945/sdk/template/Azure.Template/src/Generated/Models/RoundTripModel.cs#L35-L47), because in serialization partial class, we initialize all reference types as `null`.

**Comment by annelo-msft** [comment]
@archerzz, for 1, if we don't call AsReadOnly(), the type of the property is still List<string>, and a user could cast to that and mutate the list.  We need to call AsReadOnly() to ensure the list cannot be mutated.

For 2, that is an interesting point - I expect we don't do this because we assume the server is returning correct data. @tg-msft, can you comment on how we have thought about validating server responses historically in our libraries?

**Comment by archerzz** [comment]
> @archerzz, for 1, if we don't call AsReadOnly(), the type of the property is still List, and a user could cast to that and mutate the list. We need to call AsReadOnly() to ensure the list cannot be mutated.
> 
> For 2, that is an interesting point - I expect we don't do this because we assume the server is returning correct data. @tg-msft, can you comment on how we have thought about validating server responses historically in our libraries?

Thanks. I've updated the PR to follow the original design.

**Comment by archerzz** [comment]
@annelo-msft For required read-only collection properties of output model, shall we have another internal constructor like below? Let's take the [OutputModel.cs](https://github.com/annelo-msft/azure-sdk-for-net/blob/cadl-model-readonly-property/sdk/template/Azure.Template/src/Generated/Models/OutputModel.cs) as an example.

```csharp
/// <summary> Initializes a new instance of OutputModel. </summary>
internal OutputModel()
{
    RequiredReadonlyStringList = new List<string>(0).AsReadOnly();
    RequiredReadonlyIntList = new List<int>(0).AsReadOnly();
}
```

Because:
- In https://github.com/Azure/autorest.csharp/issues/2470, it's defined that collection properties of output model should have 2 internal constructors.
- But read-only properties are excluded from the parameters of initialization constructor.
- And required collection properties should be initialized.

**Comment by annelo-msft** [comment]
Hi @archerzz, yes, let's add the internal initialization constructor to initialize readonly collections.  Thanks!

**Comment by archerzz** [comment]
The last piece `ReadonlyModel` depends on the nested model type support.

**Comment by tg-msft** [comment]
> tg-msft, can you comment on how we have thought about validating server responses historically in our libraries?

We don't validate, but we do like to code defensively.  There are cases where it's possible for things to become optional in responses in the future (i.e., the service adds a new flag and sends back a different top-level sibling in the response model), but most of the time it's to guard against poorly written swagger.
