### ISSUE TITLE
Swagger "summary" is ignored during autorest generation

### ISSUE THREAD

**Issue by dpokluda** [Azure/autorest.csharp#2388]
**Describe the issue or request**
I have a rather long method description in "description" property. I wanted to use a shorter summary in "summary" property, but autorest ignores "summary" and only uses "description" property value.

**Describe your ideas for solutions**
Use "summary" property (when present) for "summary" source code documentation and use the "description" property value as "remark" for example. In situation where "summary" swagger element is missing, fall back to "description" property value.

**Comment by pshao25** [comment]
@KrzysztofCwalina could you help check below fix is OK for you, or you have any other ideas?

We will use the "summary" property for "summary" source code documentation if it exists, otherwise we still use "description" property. 

And do you think it should only applies to DPD or it should apply to all?

**Comment by KrzysztofCwalina** [comment]
Would it make sense to put summary in summary and description in remarks?
