### ISSUE TITLE
[P0][Bug] The serialization will fail if we change a string type to BinaryData

### ISSUE THREAD

**Issue by Yao725** [Azure/autorest.csharp#2447]
We changed the type of string to BinaryData at some times. Here is one example of [Cdn](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/cdn/Azure.ResourceManager.Cdn/src/Generated/Models/WafPolicySettings.cs#L44). Unfortunately, currently our serialization code will fail in such case because we will try to [parse](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/cdn/Azure.ResourceManager.Cdn/src/Generated/Models/WafPolicySettings.Serialization.cs#L51-L55) the string, but it isn't a valid json value.

Considering that this has impact on the packages with stable version, I think we should fix it ASAP.

**Comment by m-nash** [comment]
@Yao725 can you provide the code snippet that caused the failure?

**Comment by m-nash** [comment]
It looks like the issue stems from how a customer might try to set a value.

Lets say we have a simple model
```c#
    public class ModelWithBinaryData : IUtf8JsonSerializable
    {
        public string A { get; set; }
        public BinaryData Properties { get; set; }

        private ModelWithBinaryData(string a, BinaryData properties)
        {
            A = a;
            Properties = properties;
        }
    }
```

When a customer constructs a `ModelWithBinaryData` intellisense will show them they have 2 properties they can set.  Property `A` is pretty straightforward as its just a string, but `Properties` is a BinaryData and lets say in this case it can be either a complex object OR a raw string.  If the customer wants to set it to a raw string I think intellisense will lead them down using the constructor for BinaryData which takes a string OR they might try to use the static method `FromString`.

![image](https://user-images.githubusercontent.com/64171366/184719898-a7d51840-84ef-4775-8a98-234721e5c17d.png)

The issue is if a customer uses this then when they serialize the object they will get
`{"a":"a.value","properties":1}`
And what they would have expected is
`{"a":"a.value","properties":"1"}`

If instead they used the static method `FromObjectAsJson` and passed their string value into this method the BinaryData will now interpret the object correctly and calling serialize will result in the expected value.

The reason we have this discrepancy is because our serializer Utf8Json serializer assumes the BinaryData is always serializable to or from json.  As an example if a customer used the string ctor but passed in `"\"1\""` then it works the same way as `FromObjectAsJson` and we get the expected serialized result.  Same goes for a stream or raw bytes, if they aren't in json format the expected serialized content may not meet their expectations.

**Comment by m-nash** [comment]
Given that this problem is related to confusion around usage of the APIs we at minimum want to add some additional documentation on all properties of type `BinaryData` to better indicate to the user how they should set values of either object or primitives.

Lets add the following to the summary documentation for all BinaryData properties in the autogenerator
```
        /// <para>
        /// To assign an object to this property use <see cref="BinaryData.FromObjectAsJson{T}(T, System.Text.Json.JsonSerializerOptions?)"/>.
        /// </para>
        /// <para>
        /// To assign an already formated json string to this property use <see cref="BinaryData.FromString(string)"/>.
        /// </para>
        /// <para>
        /// Examples:
        /// <list type="bullet">
        /// <item>
        /// <term>BinaryData.FromObjectAsJson("foo")</term>
        /// <description>Creates a payload of "foo".</description>
        /// </item>
        /// <item>
        /// <term>BinaryData.FromString("\"foo\"")</term>
        /// <description>Creates a payload of "foo".</description>
        /// </item>
        /// <item>
        /// <term>BinaryData.FromObjectAsJson(new { key = "value" })</term>
        /// <description>Creates a payload of { "key": "value" }.</description>
        /// </item>
        /// <item>
        /// <term>BinaryData.FromString("{\"key\": \"value\"}")</term>
        /// <description>Creates a payload of { "key": "value" }.</description>
        /// </item>
        /// </list>
        /// </para>
```

Resulting intellisense will be
![image](https://user-images.githubusercontent.com/64171366/184996116-08d7b101-9e65-4fc0-9a92-f49a05587724.png)
