### ISSUE TITLE
CADL+DPG support of basic types of cadl-azure-core

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.csharp#2450]
CADL provides a library of type part of "cadl-azure-core". [This is an example](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAYXp1cmUtdG9vbHMvY2FkbC3GEWNvcmUiOwrJJ8UbbGFuZy9yZXN0IjsKdXNpbmcgQcQtLkNvcmUuT3BlcmF0aW9uczsKCm1vZGVsIEVucm9sbG1lbnQgewogIEBrZXnEB0NhZGwuUmVzdC5zZWfEHigiZckqcyIpCiAgaWQ6IHN0cmluZzsKfdJPR3JvdXDMVNUwUmVnaXN05wCV2y5pbnRlcmZhY2UgSW90RHBzUmVzb3VyY2VMaWZldGltZTxUyBI%2BxUZvcCBjcmVhdGUgaXMgyBtDxRJPclJlcGxhY8w0O8YzcmVhZMwxUmVhZNImZGVsZc5ZRMUS0ipsaXN0zChMaXN0zSZ9CgrmAWtIdHRwLnJvdXRlKCIv7gFq6gD76gFdcyBleHRlbmRz%2BAEPyivpARBhdHRl7gCPQWPkAXfLLCwgeyBzb21lUGFyYW3oAYAgfcgXUmVzdWx0yhj%2FAMHpAgb4AMbGHf8Ay%2BsAn8UwPiB71nVy7AJLzXLtAmXqAwTfeTzNN8R3OwoK).

When people are using "cadl-azure-core", it automatically creates a model called `Azure.Core.Operations.Error` which is always the same everywhere. This information should be used to link to an actual SDK `Azure.Core` class to avoid duplication.

This issue should fill two purposes:
- Make sure Azure.Core has what it needs to represent `Azure.Core.Operations.Error`
- Plug the codegen to use Azure.Core and not generated types when those classes are recognized.

This is not AugustMVP scoped.

Example of Swagger generated from those types for clarity:
```
    "Azure.Core.Operations.Error": {
      "type": "object",
      "properties": {
        "code": {
          "type": "string",
          "description": "One of a server-defined set of error codes."
        },
        "message": {
          "type": "string",
          "description": "A human-readable representation of the error."
        },
        "target": {
          "type": "string",
          "description": "The target of the error."
        },
        "details": {
          "$ref": "#/definitions/Azure.Core.Operations.Error",
          "description": "An array of details about specific errors that led to this reported error."
        },
        "innererror": {
          "$ref": "#/definitions/Azure.Core.Operations.InnerError",
          "description": "An object containing more specific information than the current object about the error."
        }
      },
      "description": "The error object.",
      "required": [
        "code",
        "message",
        "details"
      ]
    },
    "Azure.Core.Operations.ErrorResponse": {
      "type": "object",
      "properties": {
        "error": {
          "$ref": "#/definitions/Azure.Core.Operations.Error",
          "description": "The error object."
        }
      },
      "description": "A response containing error details.",
      "required": [
        "error"
      ]
    },
    "Azure.Core.Operations.InnerError": {
      "type": "object",
      "properties": {
        "code": {
          "type": "string",
          "description": "One of a server-defined set of error codes."
        },
        "innererror": {
          "$ref": "#/definitions/Azure.Core.Operations.InnerError",
          "description": "Inner error."
        }
      },
      "description": "An object containing more specific information about the error. As per Microsoft One API guidelines - https://github.com/Microsoft/api-guidelines/blob/vNext/Guidelines.md#7102-error-condition-responses.",
      "required": [
        "code"
      ]
    },
```

**Comment by lirenhe** [comment]
@chunyu3, @AlexanderSher , could you work together on the design for this? 
There are a couple of decorators and models defined in cadl-azure-core, for most of them, I don't think we need to generate seperate model for them, we should leverage the predefined models in the core library.

**Comment by chunyu3** [comment]
We will generate those models in a common library(e.g. azure) and import them to SDK libraries. 

- reuse already predefined models in azure.core library: need an approach to figure out if there are any mapping type (via compare the schema)
- Add those models in cadl-azure-core gradually. When we find a new type needed, we will add it into the common library.

**Comment by lirenhe** [comment]
@chunyu3,  could you create a list of items that we already supported and plan to support for 2.0beta2?

**Comment by ArcturusZhang** [comment]
We currently have two possible approaches to implement this:
1. If we have the plan to let Azure.Core also be generated from its corresponding cadl file (for instance, generate the models and interfaces in `Azure.Core` from `cadl-azure-core`), we could do this replacement in the emitter, so that the generator does not have to worry about which model I need to replace with something else, and which model does not need to be output because it gets replaced. Before we could generate azure.core from cadl, the mapping for replacing candidate will have to be maintained manually.
2. We could follow similar way as what mgmt generator is doing right now. The generator could know and figure out which model from cadl should be replaced, and replace it with correct csharp type from `Azure.Core`. And since mgmt already has similar things, we might could get it for free (with minor modification) considering that we are currently trying to merge the generator code from dpg and mgmt, it might be better to do this after the merge.

**Comment by lirenhe** [comment]
@ArcturusZhang, I reopened this one and could you help to 
handle the ask in https://apiview.dev/Assemblies/Review/0eacd79245e14c6fa88d5991aac2e02f#914b8217b76c4d9096cd8b0f0af50e30

**Comment by ArcturusZhang** [comment]
> @ArcturusZhang, I reopened this one and could you help to handle the ask in https://apiview.dev/Assemblies/Review/0eacd79245e14c6fa88d5991aac2e02f#914b8217b76c4d9096cd8b0f0af50e30

This is mainly because they defined a model in cadl that is very like to the error in cadl-azure-core.

After checked all the models defined in cadl-azure-core, except for error related models, in dotnet SDK's design, none of them will be designed to be part of the public api. Since we have the `post processor` which trims the SDK's public interface, we are not very worried about this any more.
If there are new models that we should add into azure.core library and replace them in our generator, we could open a new issue for them.
Close this one for now.
