### ISSUE TITLE
Errors present in Appconfiguration generated client

### ISSUE THREAD

**Issue by DivineNwaokocha** [Azure/autorest.csharp#2452]
**Library name**
Azure.Data.Appconfiguration

**Describe the bug**
When we generate the client and build the solution, the following contradicting errors occur referencing two different constructors. (Image of the code is attached) The client is generated by the autorest generator and the error is produced by the analyzer.

AZC0007	A client type should have a public constructor with equivalent parameters that doesn't take a Azure.Core.ClientOptions-derived type as the last argument

AZC0006	A client type should have a public constructor with equivalent parameters that takes a Azure.Core.ClientOptions-derived type as the last argument

The client is generated using the following swagger: 

Input File :  -  https://github.com/Azure/azure-rest-api-specs/blob/e01d8afe9be7633ed36db014af16d47fec01f737/specification/appconfiguration/data-plane/Microsoft.AppConfiguration/stable/1.0/appconfiguration.json

**Expected behavior**
Solution build should succeed with no errors

**Actual behavior**
Solution build fails due to the two outlined errors.

![Error_desc](https://user-images.githubusercontent.com/51302786/180071808-79043408-7186-48fd-bb44-dd40cfc91ad6.png)

![Error 0006](https://user-images.githubusercontent.com/51302786/180071811-7645328d-aff2-4c50-9e6c-e6ad57fdf0bc.png)

![error 0007](https://user-images.githubusercontent.com/51302786/180071812-4e84756c-fce0-40bd-be0f-1d4921d7fd4b.png)

**Comment by jsquire** [comment]
@lirenhe:  Would you be so kind as to assist, please?

**Comment by pshao25** [comment]
This scenario is currently not in the scope of https://github.com/Azure/autorest.csharp/issues/2105 because it has optional global parameter. It is in the scope of https://github.com/Azure/autorest.csharp/issues/2055. @annelo-msft do we need to support it now?

The error comes from the [analyzer](https://github.com/Azure/azure-sdk-tools/blob/main/src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ClientConstructorAnalyzer.cs). This must be updated after we implement https://github.com/Azure/autorest.csharp/pull/2128

@DivineNwaokocha there is a workaround for you to suppress it temporarily. https://github.com/Azure/azure-sdk-for-net/blob/ae550cb5d4be459e61d0f42f46c00033b0fc9a83/sdk/resourcemanager/Azure.ResourceManager/src/ArmClient.cs#L45-L47

**Comment by jsquire** [comment]
> do we need to support it now?

Since the mitigation is just to suppress the analyzer rule, I think it's safe to wait on this one.   Thanks for looking into it, @pshao25.

**Comment by chunyu3** [comment]
@AlexanderSher and @annelo-msft  will discuss this in arch board meeting: clarify the guideline for client constructor , then update analyzer rule to consistent with guideline if needed.

**Comment by lirenhe** [comment]
@chunyu3, @pshao25,  seems this problem happens for multiple service teams, is there any conclusion related to those analyzer rule?

cc @m-nash

**Comment by chunyu3** [comment]
duplicate with https://github.com/Azure/autorest.csharp/issues/3706
