### ISSUE TITLE
Generate ModelFactory for mocking, from DPG packages

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2461]
Per the [.NET Guidelines for Mocking](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-mocking-factory-builder), .NET client libraries with models will need to provide factories for constructing model graphs from virtual methods.

Design TBD.

#### Design Notes/Questions
- Curiously, the HLC generator only generates a model factory if output models are defined the REST API.  Is this behavior that we want to preserve?

**Comment by lirenhe** [comment]
@ArcturusZhang, as you are working on the similar item for mgmt. SDK, assign this to you.  Nice to have for 2.0beta2

**Comment by ArcturusZhang** [comment]
Related work on mgmt plane tracking in this issue: https://github.com/Azure/autorest.csharp/issues/2112

**Comment by ArthurMa1978** [comment]
Close it as this is tracked by feature https://github.com/Azure/autorest.csharp/issues/2112.

**Comment by lirenhe** [comment]
Reopen it as it is targeting for DPG.

**Comment by m-nash** [comment]
depends on https://github.com/Azure/autorest.csharp/pull/2831

**Comment by ArcturusZhang** [comment]
Depending on https://github.com/Azure/autorest.csharp/issues/3178

I really hate to add a lot of if clauses in the `ModelFactoryTypeProvider` because the disalignment we have in above issue, therefore the model factory for mgmt/HLC has issues in DPG.
Therefore I plan to resolve the above issue first so that the model factory for mgmt/HLC could smoothly apply to DPG as well.
