### ISSUE TITLE
Generate models with collections of model types from Cadl

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2490]
### Round-trip model with collection type properties
This issue tracks the work to implement generation of round-trip models with that have properties that are collections of models.

Input and output models with properties that are collections of models should be generated as well as P1 (rather than P0), based on generalization of the rules described here and for input/output models with collection properties.

#### Input Cadl file
[Cadl testserver models/collections-models](https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/models/collections-models/main.cadl#L36-L44)

#### Expected output

- [x] [ModelCollectionModel.cs](https://github.com/annelo-msft/azure-sdk-for-net/blob/cadl-test-collection-models/sdk/template/Azure.Template/src/Generated/Models/ModelCollectionModel.cs)
- [x] [ModelCollectionModel.Serialization.cs](https://github.com/annelo-msft/azure-sdk-for-net/blob/cadl-test-collection-models/sdk/template/Azure.Template/src/Generated/Models/ModelCollectionModel.Serialization.cs)
- [x] Constructor takes initialization value for required `IEnumerable<SimpleModel>` property
- [x] Constructor initializes optional collection to `ChangeTrackingList<SimpleModel>`
- [x] Model collection properties are both of type `IList<SimpleModel>`
- [x] ModelCollectoinModel inherits from `IUtf8JsonSerializable`
- [x] IUtf8JsonSerializable.Write method is defined in serialization partial class
- [x] Write method calls `Utf8JsonWriterExtensions.WriteObjectValue` to serialize items in collection
- [x] Deserialize method is defined in serialization partial class
- [x] SimpleModel.DeserializeSimpleModel method is called to deserialize collection items

**Comment by annelo-msft** [comment]
We make the assumption that models in the collection are serializable, which may not be true for user-defined schemas like we have in search, per @tg-msft, but these are out of scope for the August MVP.  We may want to revisit when we get to https://github.com/Azure/autorest.csharp/issues/2518.

**Comment by lirenhe** [comment]
@archerzz, plesae help to verify whether our current collection generation could already cover models.  Thanks

**Comment by archerzz** [comment]
I think we have a blocking issue: there is a circular dependency between `ModelTypeProvider => TypeFactory => OutputLibrary` for collections of model type and probably (I haven't test but pretty sure) nested model type.

- In the initialization of a `ModelTypeProvider`, `typeFactory.CreateType` is invoked to [initialize properties](https://github.com/archerzz/autorest.csharp/blob/893d16802ad8c09b7fac339c86d7502d6748a682/src/AutoRest.CSharp/Common/Output/Models/Types/ModelTypeProvider.cs#L84).
- If the property is a custom type (e.g. not primitive type), then `DpgOutputLibrary.ResolveModel` is [invoked](https://github.com/archerzz/autorest.csharp/blob/893d16802ad8c09b7fac339c86d7502d6748a682/src/AutoRest.CSharp/Common/Generation/Types/TypeFactory.cs#L37).
  - That [method](https://github.com/archerzz/autorest.csharp/blob/893d16802ad8c09b7fac339c86d7502d6748a682/src/AutoRest.CSharp/LowLevel/AutoRest/DpgOutputLibrary.cs#L35-L37) relies on `IReadOnlyDictionary<InputModelType, ModelTypeProvider> _models` property of `DpgOutputLibrary`.
- The problem is that when you initialize `ModelTypeProvider`, that property is not initialized, so you'll get `System.InvalidOperationException : ResolveModel is called before models are generated.` exception.

**Comment by lirenhe** [comment]
cc @AlexanderSher

**Comment by archerzz** [comment]
The last remaining piece is the support of optional collection types which should be initialized as `ChangeTrackingList`.
