### ISSUE TITLE
Provide design for missing @doc

### ISSUE THREAD

**Issue by AlexanderSher** [Azure/autorest.csharp#2589]
In azure-sdk-for-net, we have multiple analysis rules that are enabled for missing docs (cs1591, cs1571, etc.) However, other projects may have more relaxed rules on docs requirements.
We need to decide how we treat swagger or CADL input that has missing docs
- Add a setting which, when enabled, will make generator to fail on missing doc, either in pre-autorest.csharp phase or in autorest.csharp. When disabled, just generate without doc. In azure-sdk-for-net, this setting will be enabled.
- Always generate without doc. Recommend disabling cs1591, cs1571 and other similar rules for the affected service.
- Generate stub comments as we do for HLC

**Comment by annelo-msft** [comment]
We decided in a design meeting that we would rely on Cadl to enforce this: https://github.com/Azure/cadl-azure/issues/1748.

@AlexanderSher, is the reason we're bringing this back up because we can't merge generator changes to the azure-sdk-for-net repo with missing docs while Cadl is not enforcing this requirement?

**Comment by AlexanderSher** [comment]
Yes. Well, we can, but users will be forced to disable warnings.

**Comment by annelo-msft** [comment]
Is this an issue right now when we're not generating from Cadl in azure-sdk-for-net yet?  Or does it only become an issue once https://github.com/Azure/autorest.csharp/issues/2600 is completed?  Because it looks like Cadl enforcement of doc comments may be available soon: https://github.com/Azure/cadl-azure/issues/1748

**Comment by annelo-msft** [comment]
Design provided in https://github.com/Azure/autorest.csharp/issues/2621
