### ISSUE TITLE
Generate models with "fixed enum" of int properties from Cadl

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2591]
Design TBD.

https://github.com/Azure/autorest.csharp/issues/2477 tracks the work to generate fixed enums of strings.

Related design question: https://github.com/Azure/azure-sdk-for-net/pull/30176/files#r932531328

**Comment by lirenhe** [comment]
@archerzz, I expect we shall get it after @m-nash finishes the first step of the refactoring.
Please help to verify the generated code is expected.

**Comment by archerzz** [comment]
> @archerzz, I expect we shall get it after @m-nash finishes the first step of the refactoring. Please help to verify the generated code is expected.

It doesn't work as expected... We could not generate fixed enum type for the following definition:
```typescript
@doc("Fixed integer enum")
enum FixedIntegerEnum {
    One: 1,
    Ten: 10,
    Hundred: 100,
    Thousand: 1000,
}
```

The direct root cause is in the definition of `InputEnumTypeValue`. Looks like it only supports string as value: https://github.com/Azure/autorest.csharp/blob/c157c68ff50ed5ffaa3b3e38c37bbc878b669ea4/src/AutoRest.CSharp/Common/Input/Inputs.cs#L195

The JSON parser codes confirm that: https://github.com/Azure/autorest.csharp/blob/c157c68ff50ed5ffaa3b3e38c37bbc878b669ea4/src/AutoRest.CSharp/Common/Input/CadlInputEnumTypeValueConverter.cs#L35

---

So I checked the previous behavior, and `ChoiceValue.Value` is a string as well: https://github.com/Azure/autorest.csharp/blob/c157c68ff50ed5ffaa3b3e38c37bbc878b669ea4/src/AutoRest.CSharp/Common/Input/Generated/CodeModel.cs#L1134-L1137

**Comment by archerzz** [comment]
I'll try the following solution:
- change `InputEnumTypeValue.Value` to `object`
- change JSON parsing logic to support integer value as enum value
- update `ModelWriter` to add a special path for integer enum
- shall we generate serialization class for integer enum? I think it should be supported naturally, but need to test both read and write.

**Comment by archerzz** [comment]
Looks like we might have another way pass in the string form of enum values.
- that will generate the enum types and corresponding serialization classes below (which could be excessive)
```csharp
internal static partial class FixedIntegerEnumExtensions
    {
        public static int ToSerialString(this FixedIntegerEnum value) => value switch
        {
            FixedIntegerEnum.One => 1,
            FixedIntegerEnum.Ten => 10,
            FixedIntegerEnum.Hundred => 100,
            FixedIntegerEnum.Thousand => 1000,
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, "Unknown FixedIntegerEnum value.")
        };

        public static FixedIntegerEnum ToFixedIntegerEnum(this int value)
        {
            if (Equals(value, 1)) return FixedIntegerEnum.One;
            if (Equals(value, 10)) return FixedIntegerEnum.Ten;
            if (Equals(value, 100)) return FixedIntegerEnum.Hundred;
            if (Equals(value, 1000)) return FixedIntegerEnum.Thousand;
            throw new ArgumentOutOfRangeException(nameof(value), value, "Unknown FixedIntegerEnum value.");
        }
    }
```
- the problem is in the generated parent class serialization/de-serialization codes, it cannot treat the child value correctly.
```csharp
if (Optional.IsDefined(OptionalFixedIntegerEnum))
            {
                if (OptionalFixedIntegerEnum != null)
                {
                    writer.WritePropertyName("optionalFixedIntegerEnum");
                    writer.WriteStringValue(OptionalFixedIntegerEnum.Value.ToSerialString());
                }
                else
                {
                    writer.WriteNull("optionalFixedIntegerEnum");
                }
            }
```
- maybe we can fix that problem, but is this way extensible to other further value types? and we have excessive serialization classes

**Comment by m-nash** [comment]
Have we explored making InputEnumTypeValue a generic type and restricting it to primitives?  Then InputEnumTypeValue.Value would be T.  Object allows for a lot of flexibility and I prefer to have compile time restrictions as much as possible.

If the set of "types" is small enough perhaps we could just have 2 types InputEnumTypeStringValue and InputEnumTypeIntValue?  This is extensible in the sense that if a 3rd comes along later its easy enough to add it in, but not as extensible as the generic type since it should require no new code of for instance byte is used in the future.

**Comment by archerzz** [comment]
> Have we explored making InputEnumTypeValue a generic type and restricting it to primitives? Then InputEnumTypeValue.Value would be T. Object allows for a lot of flexibility and I prefer to have compile time restrictions as much as possible.
> 
> If the set of "types" is small enough perhaps we could just have 2 types InputEnumTypeStringValue and InputEnumTypeIntValue? This is extensible in the sense that if a 3rd comes along later its easy enough to add it in, but not as extensible as the generic type since it should require no new code of for instance byte is used in the future.

@m-nash Thanks for your suggestion. From [CADL doc](https://microsoft.github.io/cadl/docs/language-basics/enums/), right now 3 types of value are supported: string, integer and float.

**Comment by m-nash** [comment]
@archerzz does CADL provide a @flags attribute for enums?  If so we might want to have our generator add the `[Flags]` attribute to those.
