### ISSUE TITLE
Generator warning doesn't list line number of Cadl file statement

### ISSUE THREAD

**Issue by annelo-msft** [Azure/autorest.csharp#2692]
Trying to generate a client from the [authoring.cadl](https://github.com/Azure/cadl-azure/blob/main/packages/cadl-samples/data-plane/language/authoring/authoring.cadl) API description, I encountered the following error:

```
PS C:\src\autorest.csharp> .\artifacts\bin\AutoRest.CSharp\Debug\netcoreapp3.1\AutoRest.CSharp.exe --standalone .\test\TestProjects\Authoring\Generated
Unhandled exception. System.Text.Json.JsonException: Enum must have a description
   at AutoRest.CSharp.Common.Input.CadlInputEnumTypeConverter.CreateEnumType(Utf8JsonReader& reader, String id, String name, JsonSerializerOptions options, ReferenceResolver resolver) in C:\src\autorest.csharp\src\AutoRest.CSharp\Common\Input\CadlInputEnumTypeConverter.cs:line 53
```

I added @doc statements to all enums and enum values in the file, but I still got the error.

Proposal: Include the line number of the Cadl file that causes the error, so generator users can successfully modify the input Cadl on failure.

**Comment by lirenhe** [comment]
Today, we required @doc on each model/operation, but in this TA/authoring case, the enum "OperationState" missed doc and it is defined in cadl-azure-core.
Before we have the linter to verify each cadl file before merging, there is no way for us to easily resolve such issues so I suggest we report warning instead of throwing error on this.

@annelo-msft , @chunyu3 , @AlexanderSher

**Comment by chunyu3** [comment]
added the enum name in the error message. The issue is resolved.
