### ISSUE TITLE
Generate .NET client from Autonomous Development Platform Cadl API description

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.csharp#2784]
This issue tracks validating that a DPG generator can generate the ADP client, models, convinience APIs and protocol methods from https://github.com/Azure/azure-rest-api-specs-pr/pull/9236/files, to achieve parity with what DPG v1.0 can generate from ADP OpenAPI description from the same PR

Inputs:
https://github.com/Azure/azure-rest-api-specs-pr/pull/9236/files

**Comment by archerzz** [comment]
I tried with cadl compiler `0.3.5` (we didn't upgrade to the latest due to some issue in test server).

The only problem met during code generation is the `@service` decorator which is only supported in the latest version of cadl compiler. I split it into the old decorators `@serviceTitle` and `@serviceVersion`.

The generated codes are here: https://github.com/archerzz/autorest.csharp/tree/dpg/adp-experiment/samples/ADP/Generated

---

Cadl compiler `0.3.5` can recognize 17 routes defined in the cadl files.
- 1 route is the `/operations/{operationId}` which we ignore
- 11 routes have corresponding protocol methods generated
- 5 routes do not have protocol methods generated; they all have `@client` decorator. I think we don't support `@client` right now.

**Comment by archerzz** [comment]
PR on `azure-sdk-for-net`: https://github.com/Azure/azure-sdk-for-net/issues/32466

**Comment by archerzz** [comment]
New PR of ADP CADL on `azure-rest-api-specs-pr`: https://github.com/Azure/azure-rest-api-specs-pr/pull/9634

**Comment by lirenhe** [comment]
No furthur work needed for ADP, close this item.
