### ISSUE TITLE
Cannot generate scope method when this method doesn't belong to any resources in mgmt plane

### ISSUE THREAD

**Issue by Yao725** [Azure/autorest.csharp#2790]
It looks like the generator omitted some scope methods when we cannot find the resource corresponding to these methods in the current RP. Below are some examples about the methods that we missed.
[HelpRP](https://github.com/Azure/azure-sdk-for-net-pr/pull/1839):
```
/{scope}/providers/Microsoft.Help/checkNameAvailability
/{scope}/providers/Microsoft.Help/discoverySolutions
```
Cunsumption:
```
/{scope}/providers/Microsoft.Consumption/usageDetails
```

**Comment by siddiavinashmsft** [comment]
Hey Team, 

I have an update. We have a new namespace called "SelfHelp" before it was called "HelpRp". [Board Review PR](https://github.com/Azure/azure-sdk/issues/5817).

Therefore, I have re generated the SDK's: 

- New Draft PR - [SelfHelp](https://github.com/Azure/azure-sdk-for-net-pr/pull/1861)
- Public Spec Link - azure-rest-api-specs - [Microsoft.Help](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/help/resource-manager)

Now it turns out we can generate code for:
`/{scope}/providers/Microsoft.Help/checkNameAvailability`

We still **cannot generate** for:
`/{scope}/providers/Microsoft.Help/discoverySolutions`

CC: @ArcturusZhang @ArthurMa1978

**Comment by ArthurMa1978** [comment]
@siddiavinashmsft  when do you expect to release the sdk, @ArcturusZhang  is working on the fix, but still take some time.

**Comment by ArcturusZhang** [comment]
I am working the fix here: https://github.com/Azure/autorest.csharp/pull/3259
