### ISSUE TITLE
CADL: The mixed use of template & non-template for operations would case codegen error

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.csharp#2800]
Repro:
1. Use the attached package
2. Execute npm install & cadl compile . --emit @azure-tools/cadl-csharp

expect:
Code are generated successfully.

Actual:
Unhandled exception. System.ArgumentException: An item with the same key has already been added. Key: apiVersion

If I removed the line of  `op delete is ResourceDelete<Pet>;`, compile succeed again.

[petstore.zip](https://github.com/Azure/autorest.csharp/files/9837039/petstore.zip)

**Comment by ArcturusZhang** [comment]
Root cause: when we are mixing the template and non-template operations, the generated api-version parameter is different in the emitter output.
In the `read` or `create` operation (non-template), the api-version parameter has the name `apiVersion`:
```
{
       "$id": "41",
       "Name": "apiVersion",
       "NameInRequest": "api-version",
       "Description": "",
       "Type": {
        "$id": "42",
        "Name": "String",
        "Kind": "String",
        "IsNullable": false
       },
```
In the `delete` operation (template), the api-version parameter has the name `api-version`:
```
{
       "$id": "27",
       "Name": "api-version",
       "NameInRequest": "api-version",
       "Description": "The API version to use for this operation.",
       "Type": {
        "$id": "28",
        "Name": "string",
        "Kind": "String",
        "IsNullable": false
       },
```

**Comment by lirenhe** [comment]
No real service is impacted by this, move to GA
