### ISSUE TITLE
[BUG] Should not generate response type as Response<object>

### ISSUE THREAD

**Issue by m-nash** [Azure/autorest.csharp#2924]
In this [PR](https://github.com/Azure/azure-sdk-for-net/pull/32939/files#diff-65e078bf8d70813d9ba2994fc03149c59ffbdf2879a07b769508bb96da9b5c61R4150) we are generating a method as
```c#
public virtual Response<object> CreateOrReplaceDataStreamStorage(string measurementId, string dataStreamId, StorageCreationParameters body = null, CancellationToken cancellationToken = default)
```
Which will create compilation errors when we try to deserialize the T [here](https://github.com/Azure/azure-sdk-for-net/pull/32939/files#diff-65e078bf8d70813d9ba2994fc03149c59ffbdf2879a07b769508bb96da9b5c61R4157)

**Comment by lirenhe** [comment]
@pshao25 , this item blocks ADP onboarding, please work on this with high priority. thanks

**Comment by pshao25** [comment]
Corresponding cadl:
```
@segmentOf(Storage)
createOrReplace is CustomSingletonResourceCreateOrReplace<
  Storage,
  CustomBodyWrapper<StorageCreationParameters>,
  StorageBase
>;
```
where the `CustomSingletonResourceCreateOrReplace` is:
```
@createsOrReplacesResource(TResource)
@autoRoute
op CustomSingletonResourceCreateOrReplace<
  TResource extends object,
  TParams extends object,
  TResponse extends object = TResource
> is Foundations.ResourceCollectionOperation<
  TResource,
  TParams,
  CustomResourceCreatedOrOkResponse<TResponse>
>;
```
**Pay attention it is marked as a `Storage` resource by `@createsOrReplacesResource(TResource)`.**

And the response it wants to pass to `Foundations.ResourceCollectionOperation` is `CustomResourceCreatedOrOkResponse<TResponse>`
```
alias CustomResourceCreatedOrOkResponse<T extends object> = CustomResourceCreatedResponse<T> | CustomResourceOkResponse<T>;

model CustomResourceCreatedResponse<T extends object> {
  ...Cadl.Http.Response<201>;
  @body body: T;
}

model CustomResourceOkResponse<T extends object> {
  ...Cadl.Http.Response<200>;
  @body body: T;
}
```
where `T` is `StorageBase` instead of `Storage`.

**Question:**
What is the expected return model for this operation? `Storage` or `StorageBase`?

**Comment by m-nash** [comment]
As defined it appears it should be `StorageBase`, but maybe I am not following why there is ambiguity here.

**Comment by pshao25** [comment]
> As defined it appears it should be `StorageBase`, but maybe I am not following why there is ambiguity here.

This operation is marked as `@createsOrReplacesResource(Storage)`. We have a decision before, if an operation is marked as a resourse, its return type is that resource. @chunyu3 has more context about that decision.

**Comment by imakhlin** [comment]
> This operation is marked as `@createsOrReplacesResource(Storage)`. We have a decision before, if an operation is marked as a resourse, its return type is that resource.

IMO, API developer should be able to customize the response type event if this is an operation on a resource, otherwise it makes no sense to use the resource abstraction. For example, we have a resource where some fields are defined as "secrets" and GET for this resource should return a model without sensitive fields, on the other hand there is a POST action for users that have access right to see the sensitive information on this resource - response model in this case will be different.

**Comment by pshao25** [comment]
Current status summary:
1. @imakhlin I saw you change the return type from `StorageBase` to `Storage` in the latest [PR](https://github.com/Azure/azure-rest-api-specs-pr/pull/10336). It seems a short term solution (if it is urgent), right?
2. @m-nash we could change the current behavior from returning resource type to returning response type in the long term. There are two solutions:
2.1 We give the template a friendly name as [what `Page<T>` has already done](https://github.com/Azure/cadl-azure/blob/154e09a3f379cbce769d27f1d62f2e73dfd6c5ba/packages/cadl-azure-core/lib/models.cadl#L9). An example PR is [here](https://github.com/Azure/cadl-azure/pull/2383).
2.2 We workaround at our side to concatenate the template name and its arguments. PR [here](https://github.com/Azure/autorest.csharp/pull/2966). This could also resolve the issue https://github.com/Azure/autorest.csharp/issues/2683.

**Comment by m-nash** [comment]
I am not sure I follow exactly how we end up with `object`.  If the earlier decision was to always use the `Resource` then why didn't we do that?  Is this a special combination of factors that lead to the issue?  Is it because `StorageBase` is never emitted as a model?  Why is that?

In general I don't think "deciding the actual return type" is a decision the dotnet generator / emitter should be making.  We should get a reliable answer from cadl that we simply use.  Otherwise any logic around this would need to be duplicated for N languages unless I am missing something.

@lmazuel FYI?

**Comment by pshao25** [comment]
@m-nash 

> I am not sure I follow exactly how we end up with object.

We generate `object` because the model `Storage` in `cadl.json` has `"Usage": "None"`. Why the usage is none? Because in current implementation we make resource type `Storage` as return type, while the [`resolveUsages`](https://github.com/pshao25/autorest.csharp/blob/8410bd784019dd09c7083cb752b2346b5ff5f6b4/src/CADL.Extension/Emitter.Csharp/src/lib/model.ts#L597) doesn't regard `Storage` as used model, it regards response type `StorageBase` as used model.

> If the earlier decision was to always use the Resource then why didn't we do that?

Seems no one (the service team, the cadl owner, emitted swagger) likes this decision now. We could rethink the previous decision since it is more like a workaround before, and we already have a solution to the previous issues now.

> In general I don't think "deciding the actual return type" is a decision the dotnet generator / emitter should be making.

I agree. Actually we have a discussion here: https://teams.microsoft.com/l/message/19:906c1efbbec54dc8949ac736633e6bdf@thread.skype/1670837861389?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1670837861389&teamName=Azure%20SDK&channelName=Cadl%20Discussion%20%F0%9F%90%AE&createdTime=1670837861389&allowXTenantAccess=false

**Comment by chunyu3** [comment]
1. Generate  `response type` as method return type.
2. List operation template which has problem with the return type name, and resolve them

**Comment by pshao25** [comment]
Close this issue because we don't need this now. 

Next time if it comes to the similar issue, there is a solution:
Change 
```
model CustomResourceCreatedResponse<T extends object> {
  ...Cadl.Http.Response<201>;
  @body body: T;
}
```
To 
```
alias CustomResourceCreatedResponse<T extends object> = Cadl.Http.Response<201> & T;
```
