### ISSUE TITLE
cadl compile seems to fail due to casing

### ISSUE THREAD

**Issue by jpalvarezl** [Azure/autorest.csharp#3001]
**Describe the issue or request**
While attempting to compile as shown in the image:

![image](https://user-images.githubusercontent.com/11056031/211859884-6bacfe7f-6d91-452c-98c5-17e1d3b78c39.png)

It fails with what it seems like an error related to the casing in the cadl file. You can find the cadl I am attempting to compile [here](https://github.com/jpalvarezl/azure-rest-api-specs/tree/feature/cognitiveservices/openai-cadl/specification/cognitiveservices/OpenAI.Inference)

**Describe your ideas for solutions**
We would like to emit the C-sharp code as expected from the cadl, while maintaining the casing we've used as we need to match the naming of the public OpenAI endpoints ([embeddings](https://beta.openai.com/docs/api-reference/embeddings) and [completions](https://beta.openai.com/docs/api-reference/completions)).

**Comment by chunyu3** [comment]
It is because the `EmbeddingsRequest ` and `CompletionsRequest` are alias, and alias will not be emitter into type graph in cadl compiler. As a result, the name is empty which cause the crash.

We are working on the feature `flatten alias` , and it will be released soon. After we support that feature, the issue will be resolved.

**Comment by chunyu3** [comment]
We have support `flatten alias` feature. And this issue will be resolved.
