### ISSUE TITLE
Is Autorest for non Azure SDK work also?

### ISSUE THREAD

**Issue by jamo-semler** [Azure/autorest.csharp#3235]
**Describe the issue or request**
We continuously hit problems/changes, when we use AutoRest to generate C# clients for consuming OpenAPI described APIs.

- Is Autorest considered an internal Azure tool?

A couple of years ago Autorest was bundled with Visual Studio, so my company went along and made Autorest the tool of choice.

**Describe your ideas for solutions**
Clarify if Autorest is for Azure SDK internal work only.
If not how *not* to be impacted by design decisions made by the team (ex. https://github.com/Azure/autorest.csharp/issues/3179).

If it is considered internal, then there need to be a clearly recommended aproach to generate OpenAPI clients going forward.

**Comment by chunyu3** [comment]
Hello @jamo-semler  We scan use Autorest to generate SDK from OpenAPI spec (swagger). What are the problems you met with?

**Comment by jamo-semler** [comment]
Hello @chunyu3 - Our problem is that there are ongoing breaking changes (or behavior changes) a good example is #3179, where we cant generate both public clients and the models. So it seems rather unstable (properbly because of changes in the Azure SDK guidelines).

**Comment by chunyu3** [comment]
Hello @jamo-semler , we block to set both `public-client` and `generation1-convenience-client` true. That means it is not allowed to generate public clients for `generation1-convenience-client` (HLC) SDK. We only allow to generate internal clients and models from autorest for data-plane.

**Comment by jamo-semler** [comment]
@chunyu3  and that broke our client generation, because they relied on exactly that combination - hence my question of Autorest is considered an internal Microsoft tool only or should/can it be used by others (stable development and minor breaking changes).

**Comment by dsynclabsllc** [comment]
I've had nothing but problems ever since they started rolling out their new csharp generators. The lack of public constructor support is extremally infuriating. Let me decide if I want to make my code public or not; it's ridiculous to put that constraint on it. All I want to do is have my custom VS extension generate a client and have it just work. But nope, there are always problems. I can't get the generator to actually create properties unless I make the --output-folder be a folder inside of the csproj folder. If I create a temporary directory and use that as the output folder path, then the model classes have no properties!

`autorest --use:@autorest/csharp@3.0.0-beta.20230208.1 --input-file="C:\Users\DevOpsUser\AppData\Local\Temp\AutoRestConnectedService\2023_May_15_11_44_39\swagger.json" --add-credential --csharp --v3 --namespace="RLC.DevOps.Runner.HealthMonitorNotes.Connected_Services.HealthMonitor" --override-client-name="HealthMonitor" --output-folder="C:\Users\DevOpsUser\AppData\Local\Temp\AutoRestConnectedService\2023_May_15_11_44_39" --generation1-convenience-client --public-clients:true --skip-csproj:true`

This outputs the model:
`namespace RLC.DevOps.Runner.HealthMonitorNotes.Connected_Services.HealthMonitor.Models
{
    /// <summary> The ApplicationDto. </summary>
    public partial class ApplicationDto
    {
    }
}
`
If I run that command with the project folder path: 
`
autorest --use:@autorest/csharp@3.0.0-beta.20230208.1 --input-file="C:\Users\DevOpsUser\AppData\Local\Temp\AutoRestConnectedService\2023_May_15_11_44_39\swagger.json" --add-credential --csharp --v3 --namespace="RLC.DevOps.Runner.HealthMonitorNotes.Connected_Services.HealthMonitor" --override-client-name="HealthMonitor" --output-folder="D:\s\toolrunners-2\tasks\RLHealthMonitor\_runner\RLC.Devops.Runner.HealthMonitorNotes\Connected Services\HealthMonitor" --generation1-convenience-client --public-clients:true --skip-csproj:true
`
Then it properly generates the model:
`
namespace RLC.DevOps.Runner.HealthMonitorNotes.Connected_Services.HealthMonitor.Models
{
    /// <summary> The ApplicationDto. </summary>
    public partial class ApplicationDto
    {
        /// <summary> Initializes a new instance of ApplicationDto. </summary>
        public ApplicationDto()
        {
        }

        /// <summary> Initializes a new instance of ApplicationDto. </summary>
        /// <param name="name"></param>
        internal ApplicationDto(string name)
        {
            Name = name;
        }

        /// <summary> Gets or sets the name. </summary>
        public string Name { get; set; }
    }
}
`
`

So many problems. So now if you want a connected service you have to somehow save the connectedservice.json file in memory, choose the purge output folder option, then save it back. I haven't tested this yet, but this is just an idea to work around it - I've tried almost every version from 20230514.1 all the way back to Feb and they all behave the same way.

**Comment by cuteribs** [comment]
I have to keep using `--legacy` to generate API clients to avoid unnecessary Azure dependencies.

Autorest could be the best OpenAPI client generator for all the common languages, but it go on the other way.

**Comment by dsynclabsllc** [comment]
> I have to keep using `--legacy` to generate API clients to avoid unnecessary Azure dependencies.
> 
> Autorest could be the best OpenAPI client generator for all the common languages, but it go on the other way.

Yep. No idea what they are thinking. It was a great tool and now it is terrible. They really felt it was necessary to show how one goes about over engineering something.

**Comment by jamo-semler** [comment]
To make it even worse. Microsoft has a competitor to the same use case (but from the Graph SDK team, Autorest is from the Azure SDK team) called Kiota - https://learn.microsoft.com/en-us/openapi/kiota/overview

**Comment by dsynclabsllc** [comment]
> To make it even worse. Microsoft has a competitor to the same use case (but from the Graph SDK team, Autorest is from the Azure SDK team) called Kiota - https://learn.microsoft.com/en-us/openapi/kiota/overview

Oh wow. Thank you! This might finally be the end of me having to use this once great, but now terrible tooling! I will give this a try this week.

**Comment by brnbs** [comment]
It's evident that nowadays AutoRest is not intended for public usage, another somewhat good alternative is openapi-generator via docker: https://github.com/OpenAPITools/openapi-generator#16---docker

**Comment by darrelmiller** [comment]
Hey @jamo-semler !  As one of the original creators of Kiota and also a contributing editor to the OpenAPI specification, I hope we are not making things worse.  I do understand your frustration.  However, I think it is important to acknowledge that the Azure SDK team has a massive set of APIs to support and it is extremely difficult to provide first class support to all those APIs and at the same time supporting any arbitrary API.

Our Kiota team is working under different constraints that make it a bit easier to justify to our management chain the additional cost of developing a purely standards based API client generator.  If you compare the experience of the Azure SDKs to the Kiota generated code, you will see there are some tradeoffs to make in terms of usability in the name of adherence to standards.

Personally, I think the cost of some DevX for consistency of experience is worthwhile. But not everyone agrees.  I also think over time we can make the gap narrower.

What I can tell you is that, we the Kiota team are committed to building the best possible API client code generators for any OpenAPI description, and we will be working hard to take advantage of the capabilities introduced in future version of OpenAPI.  I can also say that the Azure DevX team are building the most awesome API Design language with https://microsoft.github.io/typespec/ that can output OpenAPI descriptions and if you haven't tried it, you absolutely should.  TypeSpec and Kiota go together like peaches and cream. https://devblogs.microsoft.com/azure-sdk/describing-a-real-api-with-cadl-the-moostodon-story/

**Comment by jamo-semler** [comment]
@darrelmiller  Thanks for your feedback and insights into the strategy behind Kiota. It seems Kiota is a better fit for non Azure SDK teams to use for OpenAPI client generation.
