### ISSUE TITLE
CodeGenSuppressTypeAttribute appears to be ignored

### ISSUE THREAD

**Issue by rquackenbush** [Azure/autorest.csharp#3443]
**Describe the issue or request**
I am attempting to provide a custom implementation for a model in my client project. I'm attempting to prevent the generation of that type by using the `[CodeGenSuppressType]` attribute.

**Describe your ideas for solutions**
Make autorest.csharp respect the `[CodeGenSuppressType]` attribute.

**Repro Repo**
Here is a minimal example that reproduces the issue:
https://github.com/rquackenbush/AutoRestRepro

# What I've tried

### Debugging `autorest.sharp`

using the following settings in autorest.md:
```yaml
...
csharpgen:
  attach: true 
```
then stepping through the code. 

Findings:
- `GeneratedCodeWorkspace.GetSuppressedTypeNames` is only called once and it doesn't find any attributes (confirmed by calling `compilation.Assembly.GetAttributes()` without the `.Where(...)` filter.
- `GeneratedCodeWorkspace.PostprocessAsync(...)` is never called.

### Specifying values for `output-folder` and `project-folder`
This had no effect.

# Notes
- This functionality used to work in version `3.0.0-beta.20220824.2` of `autorest.csharp`.

# autorest --version

```
autorest --version
AutoRest code generation utility [cli version: 3.6.2; node: v18.7.0]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest


Showing All Installed Extensions

 Type       Extension Name                           Version      Location
 core       @autorest/core                           3.0.6306     C:\Users\rxq01\.autorest\@autorest_core@3.0.6306
 core       @autorest/core                           3.6.2        C:\Users\rxq01\.autorest\@autorest_core@3.6.2
 core       @autorest/core                           3.8.4        C:\Users\rxq01\.autorest\@autorest_core@3.8.4
 core       @autorest/core                           3.9.6        C:\Users\rxq01\.autorest\@autorest_core@3.9.6
 extension  @autorest/csharp                         3.0.0-beta.20210210.4 C:\Users\rxq01\.autorest\@autorest_csharp@3.0.0-beta.20210210.4
 extension  @autorest/csharp                         3.0.0-beta.20220822.4 C:\Users\rxq01\.autorest\@autorest_csharp@3.0.0-beta.20220822.4
 extension  @autorest/csharp                         3.0.0-beta.20220824.2 C:\Users\rxq01\.autorest\@autorest_csharp@3.0.0-beta.20220824.2
 extension  @autorest/csharp                         3.0.0-beta.20220916.1 C:\Users\rxq01\.autorest\@autorest_csharp@3.0.0-beta.20220916.1
 extension  @autorest/csharp                         3.0.0-beta.20220916.2 C:\Users\rxq01\.autorest\@autorest_csharp@3.0.0-beta.20220916.2
 extension  @autorest/csharp                         3.0.0-beta.20220919.1 C:\Users\rxq01\.autorest\@autorest_csharp@3.0.0-beta.20220919.1
 extension  @autorest/csharp                         3.0.0-beta.20220920.4 C:\Users\rxq01\.autorest\@autorest_csharp@3.0.0-beta.20220920.4
 extension  @autorest/csharp                         3.0.0-beta.20221007.1 C:\Users\rxq01\.autorest\@autorest_csharp@3.0.0-beta.20221007.1
 extension  @autorest/csharp                         3.0.0-beta.20221020.1 C:\Users\rxq01\.autorest\@autorest_csharp@3.0.0-beta.20221020.1
 extension  @autorest/csharp                         3.0.0-beta.20230518.1 C:\Users\rxq01\.autorest\@autorest_csharp@3.0.0-beta.20230518.1
 extension  @autorest/csharp                         3.0.0-beta.20230523.1 C:\Users\rxq01\.autorest\@autorest_csharp@3.0.0-beta.20230523.1
 extension  @autorest/csharp                         3.0.0-beta.20230523.2 C:\Users\rxq01\.autorest\@autorest_csharp@3.0.0-beta.20230523.2
 extension  @autorest/csharp                         3.0.0-beta.20230523.3 C:\Users\rxq01\.autorest\@autorest_csharp@3.0.0-beta.20230523.3
 extension  @autorest/csharp                         3.0.0-beta.20230525.3 C:\Users\rxq01\.autorest\@autorest_csharp@3.0.0-beta.20230525.3
 extension  @autorest/csharp                         3.0.0-beta.20230525.4 C:\Users\rxq01\.autorest\@autorest_csharp@3.0.0-beta.20230525.4
 extension  @autorest/modelerfour                    4.15.456     C:\Users\rxq01\.autorest\@autorest_modelerfour@4.15.456
 extension  @autorest/modelerfour                    4.23.7       C:\Users\rxq01\.autorest\@autorest_modelerfour@4.23.7
 extension  @autorest/modelerfour                    4.26.0       C:\Users\rxq01\.autorest\@autorest_modelerfour@4.26.0
 extension  @microsoft.azure/autorest.csharp         2.3.91       C:\Users\rxq01\.autorest\@microsoft.azure_autorest.csharp@2.3.91
 extension  @microsoft.azure/autorest.modeler        2.3.55       C:\Users\rxq01\.autorest\@microsoft.azure_autorest.modeler@2.3.55
```

**Comment by ArcturusZhang** [comment]
Hi @rquackenbush thanks for your issue.

You have multiple issues in your project, I opened a PR to fix those: https://github.com/rquackenbush/AutoRestRepro/pull/1

1. Our package of autorest.csharp is never on the nuget, as a result if you build your project before generating any code, you will get this error:
![image](https://github.com/Azure/autorest.csharp/assets/10554446/e57ee546-c2c0-4702-8d7c-271719327efb)
Our `CodeGenXX` attributes are defined in `Azure.Core` namespace and shipped in the `Microsoft.Azure.AutoRest.CSharp` assembly as internal attributes. And you might see how the generator gets those attributes in our code: 
https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/Common/AutoRest/Plugins/GeneratedCodeWorkspace.cs#L141
It is finding an attribute by the full name. When your code cannot compile, roslyn will not throw exceptions, instead the attribute it gets will be ErrorTypeSymbol and have no namespace. This explains why when you debug the generator, the generator is not getting your attribute.
To fix this issue, you need to make sure your project could compile before generating the code. Our generator's assembly could be found in our dev feed, for instance you could add this `"https://pkgs.dev.azure.com/azure-sdk/public/_packaging/azure-sdk-for-net/nuget/v3/index.json"` to your nuget feed and everything should be solved. I tried this on my local and it works. I added a `NuGet.Config` file in my PR, and your project should compile before generating any code.
2. The generator is not reading your customization code - you will find this when you add the dev feed. This could be fixed by explicitly assign a `output-folder` variable in your command line or in the `autorest.md`. I do not know the reason for this, but it only works in this way right now. I added this in my PR in the autorest.md file.
3. Your customization class is recommended to be partial to ensure the code could always compile. We only support `IList<T>` and `IReadOnlyList<T>` for arrays therefore `int[]` will throw exceptions when you generate the code. I changed this in my PR.
4. Since you just want to add a setter to the list, you do not need to use the CodeGenSuppressType attribute because using this type, the entire generated class with the name will be removed - therefore the serialization of it is removed as well, your generated code will have runtime exception when the client is attempting to send the request. I changed the code to use `CodeGenMember` instead, this only changes that property you would like to change and keep everything else in the generated code.

Hope this could resolve your issues.

BTW the PostProcessor is not enabled when the `generation1-convenience-client` sets to `true`. We did not do it because quite a few our SDKs generated using this flag has been GA and cannot get breaking changes.

**Comment by rquackenbush** [comment]
@ArcturusZhang wow - thank you for your incredible reply and PR!

1. This was an oversight on my part when creating this reproduction. In Visual Studio, I have the `pkgs.dev.azure.com` feed configured, so I didn't need the additional configuration file. In the future I'll build with `dotnet build` to ensure that I've configured everything correctly.
2. Ahh - I had gone through several iterations of things like $(project-folder) and $(this-folder) for output-folder annd project-folder but never lined up on the right combination. This makes it much more clear.
3. Excellent points. 
4. In my attempt to create a simple reproduction, I didn't properly convey my intent to have a custom model with custom serialization. That said, you gave me all the information I needed to move forward.

Thank you!
