### ISSUE TITLE
[TypeSpec] Add an option to force System.Text.Json converter to be applied to models

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/autorest.csharp#3469]
For swagger, we can apply the value of `converter` to `x-csharp-usage`, e.g. https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventgrid/Azure.Messaging.EventGrid/src/autorest.md#apply-converters-and-update-namespace-for-system-event-data-models.

This is not possible in Typespec and is a blocker for migrating the .NET Event Grid system events from swagger to Typespec.

**Comment by ArcturusZhang** [comment]
Well we could do it by using the `CodeGenModel` attribute to append usages to a model.
But this feature is not implemented for DPG yet. My point here is that to support this, we do not need anything updated on typespec side or TCGC side, we could do it all on the dotnet side.

**Comment by ArcturusZhang** [comment]
We now believes that converter should not belong to `usage` therefore in the typespec world we no longer support the `converter` usage.
But in the meantime, we will create a decorator in TCGC's csharp namespace to let you mark a specific model needs a JSON converter.
On the other hand, since we are going to introduce the public serialization story, the converter should no longer be introduced for new models - if we are trying to solve a backward compatibility issue, we could always do that using customized code, I believe it is the case here.

**Comment by ArcturusZhang** [comment]
Hi @JoshLove-msft considering the existence of this [new public serialization feature](https://github.com/Azure/autorest.csharp/pull/3434), new libraries never need the converters any more.
And in your case, if you would like to migrate old libraries with converters (because you cannot remove the attribute otherwise breaking change), we could use customization code to add back the converters.

Therefore the generator will not implement it any more, and we plan to remove the usage `converter` when it is possible.

Close this as a "wont fix"

**Comment by live1206** [comment]
we need to implement this in both autorest.csharp and microsoft/autorest

**Comment by JoshLove-msft** [comment]
Any update on this? This is needed for the Event Grid migration. /cc @m-nash @lmazuel

**Comment by live1206** [comment]
I think https://github.com/Azure/autorest.csharp/issues/4887 will resolve this

**Comment by jsquire** [comment]
@ArthurMa1978, @m-nash:   Can we please prioritize this for delivery no later than the second week of August?

**Comment by live1206** [comment]
`@hasJsonConverter` in csharp namespace

**Comment by live1206** [comment]
This can be enabled by adding `@useSystemTextJsonConverter` to the model, [example](https://github.com/Azure/autorest.csharp/blob/8768ade539b623dfebcdd2d9bd10c983f91600c4/test/TestProjects/MgmtTypeSpec/foo.tsp#L17) can be found.
