### ISSUE TITLE
Enable mocking for extension methods

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/autorest.csharp#3493]
**Describe the issue or request**

We need to enable mocking for our extension methods in mgmt SDK. Other targets, HLC and DPG, do not have extension methods therefore they do not need this feature.

**Describe your ideas for solutions**

Our extension methods are already implemented in a "mocking friendly" way, inside the implementation of the extension method, it will redirect the call into an instance method with the same signature. Therefore the minimum work we need to do to enable mocking for extension methods in our libraries is just making those underlying "extension clients" public.

Related work: https://github.com/Azure/autorest.csharp/issues/1900
This is tracking the item that we might need to do to split the internal extension clients for clarity.

- [ ] Add xml doc
- [ ] Update MS Learn doc
- [ ] Final review with Ted and KC

**Comment by ArcturusZhang** [comment]
Some rough thoughts and designs: https://gist.github.com/ArcturusZhang/cb28882cb1e076091b8b033d49fa7743

**Comment by ArcturusZhang** [comment]
For #1900 
Our mock usually follows the following steps:
1. Find the corresponding extension client of this extension method
1. Find the underlying method calling on the corresponding extension client and mock it
1. Mock the GetCachedClient method to return the mock of the extension client

Therefore for clarity, we should have a deterministic pattern of finding the extension client from the extension method. For this reason, I believe, the current pattern, "a method extending `TenantResource`, we have a corresponding extension client of `TenantResourceExtensionClient`" is better than we split the methods on extension client.

Considering the above reason, we probably will not apply the changes requested in #1900 and will close it.

**Comment by vturecek** [comment]
@ArcturusZhang any updates on this?

A couple things to consider in this design:
1. How will it work with dependency injection?
2. Not everyone uses Moq. Integration with Moq is nice to have but it should be designed in a way that doesn't make it any harder to use without Moq.

For dependency injection, we would typically use a fake ArmClient that can create fake `ResourceGroupResource`, `SubscriptionResource`, etc.. instances. We would inject an ArmClientFactory into our classes that need to interact with ARM:

```
class Foo
{
  private readonly IArmClientFactory _clientFactory;
  public Foo (IArmClientFactory clientFactory)
  {
    _clientFactory = clientFactory;
  }

  public Task<Thing> GetSomethingFromArm()
  {
    ArmClient client = _clientFactory.CreateArmClient();
    return client.GetResourceGroupResource(..).GetThingAsync();
  }
}
```

A fake ArmClientFactory would look like this:
```
class FakeArmClientFactory : IArmClientFactory
{
  public ArmClient CreateArmClient()
  {
    return new FakeArmClient();
  }
}
```

Writing a fake ArmClient should be possible today, most of the methods we would need to fake are virtual:
```
class FakeArmClient : ArmClient
{
  public override ResourceGroupResource GetResourceGroupResource(ResourceIdentifier id)
  {
     ResourceGroupResource.ValidateResourceId(id);
     return new FakeResourceGroupResource(this, id);
  }
}
```

Then we need to fake/mock the underlying mechanism that drives the extension methods on `ResourceGroupResource`, which is the part that's not possible today:
```
class FakeResourceGroupResource
{
  ???
}
```

If all the extension methods are driven by extension clients, could those clients be inject-able in some way? For example, could they be constructor parameters to ArmClient? Then we wouldn't necessarily need to write a FakeArmClient, because we could inject fake extension clients that are used internally.

**Comment by ArcturusZhang** [comment]
> 

Our current solution does not bind with `Moq`. The idea is that mocking the extension methods takes two setups based on a built-in pattern when we implement (described in https://github.com/Azure/autorest.csharp/issues/3493#issuecomment-1614037860)

Comparing to mocking an instance method, you just need to do it in two steps. Therefore for your `FakeResourceGroupResource` implementation, you just need to do the step 3: override the `GetCachedClient` to return the `FakeResourceGroupMockingExtension` instance with your mock.

This experience is not very good I have to admit. Therefore as a starter, we plan to provide some useful utilities for `Moq` first.
