### ISSUE TITLE
Generate Batch service

### ISSUE THREAD

**Issue by chunyu3** [Azure/autorest.csharp#3549]
Generate .NET SDK for Batch

**Comment by chunyu3** [comment]
Batch typespec: https://github.com/Azure/azure-rest-api-specs-pr/tree/BatchTypeSpec/specification/batch/Batch

**Comment by archerzz** [comment]
Found 3 issues in the latest `Batch` spec in https://github.com/Azure/azure-sdk-for-java/tree/nikoudsi/batch-typespec/sdk/batch/batch-typespec:
- #3632 
- #3635 
- Need to add a new namespace: non-technical

**Comment by archerzz** [comment]
Another issue is https://github.com/Azure/autorest.csharp/issues/3638

But in `Batch`, the operation name should be wrong: https://github.com/Azure/azure-sdk-for-java/blob/6859d4e64ecf5980e0c474fd0c8160ec9b13abfb/sdk/batch/batch-typespec/routes.tsp#L2422

Its name is `GetExtensions`, but it should be `GetExtension`. So this issue can be fixed by removing the trailing `s`.
