### ISSUE TITLE
Serialized name doesn't support a string with some special char

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/autorest.csharp#3812]
This happens on some enum values, like this:

```
"type": {
          "type": "string",
          "enum": [
            "Microsoft.StorageSync/storageSyncServices"
          ],
          "x-ms-enum": {
            "name": "Type",
            "modelAsString": false
}
```

**Comment by RodgeFu** [comment]
It's not because serializedName or Transform but the ToCleanName would remove all the '_' in the name and the summary doc looks good. So close as won't fix because it should be fine for Custom code to handle this kind of special case instead of updating ToCleanName method which is used broadly without much context
