### ISSUE TITLE
[BUG] ImageSize changed to Internal after update to tsp 49

### ISSUE THREAD

**Issue by m-nash** [Azure/autorest.csharp#3836]
This diff here shows ImageSize changed to internal after updating to tsp 49 even though it is used.

https://github.com/Azure/azure-sdk-for-net/pull/39275/files#diff-b3c91385d402437b3802172c456a65b99264b90c4049dcd88f37acd4dc1b7843R14

I have fixed this with manual code for now but we should investigate / fix this.

**Comment by archerzz** [comment]
@m-nash After the investigation, I think that change is expected. I guess there used to be a bug in accessibility determination in TCGC, which has been fixed in the latest version.

Check the current `OpenAI` definition: https://github.com/Azure/azure-rest-api-specs/blob/4c38cb9966cd6afbb03c7e9b14997720a728baee/specification/cognitiveservices/OpenAI.Inference/client.tsp#L17C1-L18C39

`ImageGenerationOptions` is internal by definition, since it's **only** used by `beginAzureBatchImageGeneration` which is internal. As you can see in the definition, `@@include` is added to intentionally make it public.

However, that doesn't work in C#, because generator doesn't support `@@include`. So `ImageGenerationOptions` should be internal, and so is it's child `ImageSize` (see [here](https://github.com/Azure/azure-rest-api-specs/blob/4c38cb9966cd6afbb03c7e9b14997720a728baee/specification/cognitiveservices/OpenAI.Inference/models/images/images.tsp#L47)).

In `OpenAI` .NET SDK, we wrote [custom codes](https://github.com/Azure/azure-sdk-for-net/blob/5cbf1afe15975f2387499ade183a003f7b1d2043/sdk/openai/Azure.AI.OpenAI/src/Custom/ImageGenerationOptions.cs#L9) to make `ImageGenerationOptions`. But that won't impact the accessbility of `ImageSize`.

So in your PR, you added a snippet of custom codes to make `ImageSize` public, which is the right way to go.

I think the better way to fix it is to update the `OpenAI` typespec definitions to adopt the new accessibility decorators.

**Comment by archerzz** [comment]
The correct tsp declaration of `ImageSize` will be fixed in https://github.com/Azure/azure-rest-api-specs/pull/25856

**Comment by pshao25** [comment]
Already fixed in azure-sdk-for-net.
