### ISSUE TITLE
Prereqs are wrong

### ISSUE THREAD

**Issue by m-nash** [Azure/autorest.csharp#3870]
We required node 18+ but our prereqs say 14 https://github.com/Azure/autorest.csharp/blob/feature/v3/readme.md#prerequisites

**Comment by archerzz** [comment]
I think we only required node **16+** which comes from `typespec`. See: https://github.com/Azure/autorest.csharp/blob/cbb1b80f893b1292f715827d55ebcb97272fa4c8/package-lock.json#L1506

I can confirm that node 16 is installed on my workstation and there is no problem running `auotrest.csharp`.

However, in our pipeline, node 18+ is required due to pipeline minimal requirement.

So, we just need to update the readme to require node 16+
