### ISSUE TITLE
Nullable array defaults to empty collection.

### ISSUE THREAD

**Issue by CzapoX** [Azure/autorest.csharp#3978]
**Describe the issue or request**
I upgraded the `AutoRest` version in the project from `3.0.0-beta.20220407.1` to `3.0.0-beta.20231122.3`. The project is written using `.NET Standard 2.0`, for `LangVersion` `latest`.
`Array` marked as `nullable: true`

![image](https://github.com/Azure/autorest.csharp/assets/44379105/1ec05651-9528-4dfb-a756-6799d7daf250)

In the previous version of `AutoRest`, the library was assigning a `null` value for `JsonValueKind.Null`, this behavior is no longer present in the newest version.
![image](https://github.com/Azure/autorest.csharp/assets/44379105/cb5ba5ce-a639-4ee8-9361-c11a7825ed07)

In the latest version of `AutoRest` I get an empty collection.
![image](https://github.com/Azure/autorest.csharp/assets/44379105/68957c33-d3e2-4a90-b22c-babcaf8674b7)

**Describe your ideas for solutions**
Restore the previous behavior or provide a flag in the configurations that restores the previous behavior

**Comment by ArcturusZhang** [comment]
This relates with a decision we made a few months before. I will double confirm this with our architect.
I personally prefer the previous behavior which makes the serialization and deserialization roundtrip.

**Comment by ArcturusZhang** [comment]
Hey It turns out that there is a configuration `deserialize-null-collection-as-null-value` to control this behavior and its default value is `false` to make sure backward compatibility.
We are considering to flip its default value to `true` (not decided yet this needs more internal discussion) to make sure the default behavior is "correct".
I will update the follow ups when we have the decision.

**Comment by ArcturusZhang** [comment]
Hey I updated my above comment to have the conclusions of our discussion.
