### ISSUE TITLE
Autorest isn't handling things like <see cref="SomeClass"/> properly in generated class.

### ISSUE THREAD

**Issue by gdodd1977** [Azure/autorest.csharp#4048]
Currently I have this in my swagger file:

![image](https://github.com/Azure/autorest.csharp/assets/29410398/8e3c6f1f-df75-4ea7-9e7f-37e76bc9b42e)

But when I generate the C# code, it looks like this:

![image](https://github.com/Azure/autorest.csharp/assets/29410398/e620aeaa-b5cd-4658-a5f7-2bda56218495)

Is there something I'm doing wrong in my swagger file, or is this perhaps a bug?

Autorest version:

![image](https://github.com/Azure/autorest.csharp/assets/29410398/1a6cd626-29ea-4cd7-883b-bee08ad4ea22)

**Comment by archerzz** [comment]
@gdodd1977 This is by design. Swagger is for describing REST API, though its content will be used by generator to generate SDK including documents. `<see>` is a [.net XML doc tag](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/recommended-tags#see), which is not suitable for putting into a common API document. Right now we will only treat it like a normal html tag, so it's escaped in the generated doc.

**Comment by gdodd1977** [comment]
So is there no way to generate more complex Xml comments via this tool?

**Comment by archerzz** [comment]
> So is there no way to generate more complex Xml comments via this tool?

It can accept some Html elements which will be rendered in Microsoft doc. The main point is that it's for generic purpose, not bound to specific language feature.

**Comment by ArcturusZhang** [comment]
Hi @gdodd1977 
The reason is quite simple. The responsibility of the generator is to generate the code that could properly compile.
You could put anything in description, therefore as part of the generator's work, the generator will always escape the content of the description before writing it into generated files.
For example, in your case, what if the class `CustomerIdFormatter` does not exist? Therefore those cref part only makes sense to be added on CSharp code instead of writing them in your swaggers.
To do this, please try to customize the generated files with proper descriptions.
About how to customize the generated files, you could refer to the documentation here: https://github.com/Azure/autorest.csharp/blob/feature/v3/readme.md#replace-any-generated-member
You could just use this functionality to replace this property and you could change whatever xml doc it is now having.
