### ISSUE TITLE
Naming inconsistency

### ISSUE THREAD

**Issue by w4mhi** [Azure/autorest.csharp#4150]
**Describe the issue or request**
Generate the client classes with the command:
autorest --input-file=swagger.json --csharp --namespace=MyNamespace --add-credentials

The swagger.json has inside info:
"title": "MyTitle",
"description": "MyDescription",

The classes are generated inconsistent with name/namespace as following:
file name: MyNamespaceClientBuilderExtensions.cs
namespace Microsoft.Extensions.Azure
public static partial class MyNamespaceClientBuilderExtensions

file name: MyTitleClient.cs
namespace MyNamespace
public partial class MyTitleClient

MyTitleClientOptions.cs
namespace MyNamespace
public partial class MyTitleClientOptions : ClientOptions

**Describe your ideas for solutions**
In my opinion, the names should be consistent as the namespaces. When I use a namespace like MyCompany.MyDivision.MyProduct.MyService, the whole naming schema goes wild and the nuget representing client gets a really bad name.
What is the story with naming? Do you see a fix? Any opinion on this?

**Add labels**
workaround: Inside of the company we have hard mitigation through a PS script that change the names to align the schema.
instances: multiple, hard to onboard new services

These labels will help priority bug fixes and feature requests.

Thank you!

**Comment by ArcturusZhang** [comment]
Hi @w4mhi 
The class `MyNamespaceClientBuilderExtensions` is generated for `Azure.Core.Extension` types to consume for DI purpose, and it is by design to have the `Microsoft.Extensions.Azure` namespace. This is a requirement for **Azure** libraries, and it is not configurable.
The default namespace is controlled by the flag `--namespace`, and the client prefix, in your case it is `MyTitle`, could be controlled by the flag `--library-name=YourOwnName`. You could try to add both `--namespace` and `--library-name` to get a consistency result.
Our generator was initially designed for generating Azure libraries, therefore something is designed for generating azure libraries and might not be configurable (such as the `XXXClientBuilderExtensions`).

You may notice the library you generated now do not have models, and all the generated operations only accept a general type `RequestContent` which just accepts anything.

I believe the only thing that is unresolved is about the `XXXClientBuilderExtensions` class. There are a few workarounds you could have a try, which categorizes into two types: do not generate this type anymore or change the namespace of it if you want it.

1. we have a legacy generator, which will generate all your operations, as well as all the models that will be used by your operations. To enable it, you need to add the flag: `--generation1-convenience-client`. Because this is a legacy generator, it might have more issues than the current generator you are currently using (for instance, we might not actively resolve issues on it). Also because of this is a legacy generator, it will no longer generate the `XXXClientBuilerExtensions` class.
2. you could try to add a flag `--branded=false`, which will decouple the generated library with azure - if it works well, it will also not generate that `XXXClientBuilderExtensions` class. We are still working on this non-azure generator, therefore more issues might happen while using it, and things might change frequently.
3. we have customization files to let you tweak the generated csharp files, you could try to change the generated namespace using customized code. Here is some document about this feature: https://github.com/Azure/autorest.csharp#customizing-the-generated-code . To be specific, you need to create a partial class and put it in a place parallel with the `Generated` directory (the default output folder) like this:
```csharp
namespace YourDesiredNamespace // this is the new namespace you want to change it to
{
[CodeGenType("MyNamespaceClientBuilderExtensions")] // put the class name of the type you want to change here
public partial class YourNewClassName {} this is the new name you want to change it to
}
```

I personally recommend 1, which will solves your issue in a simplest way (and gives you models :)).

**Comment by w4mhi** [comment]
Very insightful, thank you very much for the answer. I will use the --library-name to adjust the names.
