### ISSUE TITLE
[Microsoft Generator CSharp] Generate properties and fields for Model types

### ISSUE THREAD

**Issue by ShivangiReja** [Azure/autorest.csharp#4475]
Generate properties and fields for model types. As part of this task, relocate the necessary Output types from [this location](https://github.com/Azure/autorest.csharp/tree/feature/v3/src/AutoRest.CSharp/Common/Output) as required, and generate properties and fields for model classes in the [Unbranded-TypeSpec](https://github.com/jorgerangel-msft/Microsoft.Generator.CSharp/tree/main/Microsoft.Generator.CSharp.ClientModel.TestProjects/Unbranded-TypeSpec) project.

**Comment by ArcturusZhang** [comment]
This is a bit challenging because the current implementation in this repo, either `ModelTypeProvider` or `SchemaObjectType` is actually building `ObjectTypeProperty` instead of `PropertyDeclaration`.
This is a verbose class containing too much information from input types.
We should rework the generation logic on that.
