### ISSUE TITLE
Generates duplicate switch cases with same status code

### ISSUE THREAD

**Issue by KotanaSai21** [Azure/autorest.csharp#4550]
We generated the client files using autorest. In the generated files, switch case is generated twice leading to build errors. Here is the generated code [file](https://github.com/KotanaSai21/PowerBI-CSharp/blob/d9f9522ae9ee255cbd02cff007eef3183bb82a10/sdk/PowerBI.Api/Source/ReportsRestClient.cs#L2515C22-L2516C9).

Here is the [code](https://github.com/KotanaSai21/PowerBI-CSharp/blob/d9f9522ae9ee255cbd02cff007eef3183bb82a10/sdk/swaggers/swagger.json#L7970C8-L8021C11) of the API call in swagger.json file.

Referred to multiple GitHub issues logged, but unable to figure out the reason why we're facing this issue. 
Could you please help me with this issue?

**Comment by ArcturusZhang** [comment]
Hi @KotanaSai21 
Looks like something is terribly wrong when the generator trying to deal with `file`.
We have very few cases like this in azure therefore this case might not be properly handled.
If possible, you could try to change your swagger from file to just `type: object` and see if this issue could be resolved.

If we could know if this is really caused by this `file` type response, I could make a change to fix this.

**Comment by KotanaSai21** [comment]
@ArcturusZhang, when we change the type to `type: object` and remove `"multipart/related"` from produces then it works fine and we're not getting any duplicate switch cases in the generated file. Could you please make a change to fix this? 

Also, how can we fix this error `fatal   | Error: Not able to process media type multipart/related at this moment.`  when we include ` "multipart/related"` in produces ?

**Comment by KotanaSai21** [comment]
@ArcturusZhang, as you mentioned, you will make a fix if the problem is when the type is `file`. Could you please look into this and let me know if there is any plan in making the change?

**Comment by ArcturusZhang** [comment]
@KotanaSai21 unfortunately we are short of resources, therefore we might not fix this recently, especially your SDK is using a target that we are willing to deprecate: `generation1-convenience-client: true`.

But I understand if you remove this config and regenerate you will find massive generated code change because the generator is changing the focus from swagger to typespec.

For a short term fix, I suggest you fix this manually by introduce customization code.

**Comment by ArcturusZhang** [comment]
As for the media type `multipart/related`, I assume this is not supported now by our swagger generators, and since that part has been in maintenance mode for a while, unfortunately I do not think we would support it when using swagger input any more.

If you would like to use it, I think you will have to write it manually :(

**Comment by lirenhe** [comment]
@KotanaSai21, we don't encourage Microsoft teams to use Swagger and Autorest anymore, but to use [TypeSpec](https://typespec.io/) which is our new language for API description, and it is not Azure-specific.

We are gradually stopping all effort in autorest and move to TypeSpec for CodeGen, which means new features will only be added for the TypeSpec based codegen.  Please consider doing a migration from Swagger to TypeSpec.   

cc @mario-guerra for awareness.
