### ISSUE TITLE
[ClientModel-based clients] Inconsistent "credential" versus "keyCredential" in client constructors

### ISSUE THREAD

**Issue by joseharriaga** [Azure/autorest.csharp#4555]
The `ApiKeyCredential` parameter is called "credential" in the constructor of the primary client, but it is called "keyCredential" in the constructor of the sub-clients. Not sure if there's a preference for one or the other, but I'm bringing it up mostly for the sake of consistency. 

Examples:
Important: In the examples below, it says "credential" in both cases because the generated code was edited manually for now. If the code is re-generated, the changes would be overridden, and the sub-client constructor would revert back to saying "keyCredential" as described in this issue. 

- Primary client: 🔗 https://github.com/joseharriaga/openai-in-typespec/blob/main/.dotnet/src/Generated/OpenAIClient.cs#L33
- Sub-client: 🔗 https://github.com/joseharriaga/openai-in-typespec/blob/main/.dotnet/src/Generated/Audio.cs#L36

Also, for the purposes of prioritization, note that the constructor of the sub-clients is internal by default, so this issue would only be an actual problem if the constructor were customized and made public.

**Comment by ArcturusZhang** [comment]
well @joseharriaga unfortunately I have to claim that this is by-design.
As @nisha-bhatia  has also tried, changing this results in a lot of changes.
The credential parameter in sub-clients will have the different names as you noticed, because some clients support both credentials therefore the sub-clients will accept two different credential parameters in their ctor at once. ([an example here](https://github.com/Azure/autorest.csharp/blob/ad216ac048b462cdb215430afb201cf537caede5/test/TestProjects/FirstTest-TypeSpec/src/Generated/Entity.cs#L46))
Because the ctor of sub-clients will always be internal, I believe this will not be an issue since they will never appear on the public API surface.
