### ISSUE TITLE
Properly set inits on InputType's Properties

### ISSUE THREAD

**Issue by jorgerangel-msft** [Azure/autorest.csharp#4587]
There are still input types that are not deserialized correctly due to missing init accessors on their properties. All of the input types should be adjusted so their properties are deserialized correctly. Sample where this is be done correctly: [here](https://github.com/jorgerangel-msft/Microsoft.Generator.CSharp/blob/main/Microsoft.Generator.CSharp.Input/src/InputTypes/InputNamespace.cs#L24)

**Comment by ArcturusZhang** [comment]
@jorgerangel-msft I think `init` is not enough. Since we may have cross-reference and/or self-reference in our json, they need to be `internal set` because in some circumstances we need to new the instance without value in one property and set it later because setting that missing property needs the current instance.
Examples of this case could be found when we are deserialization `InputModelType`'s `BaseModel` and `Properties` property.

**Comment by ArcturusZhang** [comment]
And I think making these input types as record does not conflict with the concept that its properties could have setter.
Records are better during debugging because it has default `ToString` implemented.
But I am fine that they are classes right now anyway
