### ISSUE TITLE
`float` is emitted as `object`

### ISSUE THREAD

**Issue by joheredi** [Azure/autorest.csharp#4683]
**Describe the issue or request**
When a spec has a `float` type it gets generated as `object`

```ts
model Foo {
   TestNonNullableFloat: float;
   TestNullableFloat: float | null;
   TestNonNullableFloat32: float32;
   TestNullableFloat32: float32 | null;
   TestNonNullableFloat64: float64;
   TestNullableFloat64: float64 | null;
}
```

![image](https://github.com/Azure/autorest.csharp/assets/21109913/b5ebb1a6-bf50-489f-a397-89e1de6e0f59)

**Describe your ideas for solutions**
Maybe generate the max possible representation which would be `decimal`

/cc: @m-nash

**Comment by ArcturusZhang** [comment]
Hi @joheredi per typespec document, `float` is the base type of `float32` and `float64`.
We did not handle this particular kind previously therefore it is emitted as `object`.
Since it is the base, from value's perspective, I think we should generate this type as `double`.
What do you think? @joheredi @m-nash
