### ISSUE TITLE
Consolidate serialization logic

### ISSUE THREAD

**Issue by live1206** [Azure/autorest.csharp#4777]
There are duplicated code in [JsonCodeWriterExtensions](https://github.com/Azure/autorest.csharp/blob/ced9b4b84e81a2daac4f7033ffd3693cd179ac67/src/AutoRest.CSharp/Common/Generation/Writers/JsonCodeWriterExtensions.cs#L160) and [JsonSerializationMethodsBuilder](https://github.com/Azure/autorest.csharp/blob/03d3cc83dd33cce6347227622e7a0eb4ec4ac544/src/AutoRest.CSharp/Common/Output/Builders/JsonSerializationMethodsBuilder.cs#L1036), they should be consolidated.

**Comment by m-nash** [comment]
I think this will automatically get fixed with the advent of https://github.com/microsoft/typespec/blob/main/packages/http-client-csharp/generator/Microsoft.Generator.CSharp.ClientModel/src/Models/Types/MrwSerializationTypeProvider.cs which will simply provide full CSharpMethod instances which contain their body statements so the writer will no longer be responsible for coming up with these.

@live1206  If you think there is still an issue after that let me know and we can discuss.

**Comment by live1206** [comment]
Looks good to me, this should be resolved while we move generator to MGC. Close this issue here.
