### ISSUE TITLE
Generated extensible enums use case-insensitive equality but case-sensitive hash codes

### ISSUE THREAD

**Issue by trrwilson** [Azure/autorest.csharp#4833]
As raised in the OpenAI .NET project: https://github.com/openai/openai-dotnet/issues/49

Extensible enums use `_value.GetHashCode()` for their `GetHashCode()` implementation while meanwhile using a case-insensitive `_value` comparison for `Equals()`. As @stephentoub points in the above issue, this is inconsistent with the conventions for `GetHashCode()` -- if two objects evaluate as equal, then they should have the same hash code.

Here's a minimal repro project to demonstrate; `npm install`, `npx tsp compile`, then `dotnet run` under "test" will demonstrate a manifestation of the problem via an unexpected `HashSet` lookup failure:

```
Hello, World!
NormalFoo == CapitalFoo     ? True
HashSet.Contains NormalFoo  ? True
HashSet.Contains CapitalFoo ? False
```

[eeHashTest.zip](https://github.com/user-attachments/files/15892873/eeHashTest.zip)

The fix may just be as simple as converting the `_value` into a matching lower invariant before calling `GetHashCode()` on it (though this could be further optimized with caching/etc.).

**Comment by ArcturusZhang** [comment]
Hi @trrwilson thanks for reporting this.
The fix is ready in this PR: https://github.com/Azure/autorest.csharp/pull/4842
netstandard2.0 provides this handy API to let us get hashcode case-insensitively: https://learn.microsoft.com/en-us/dotnet/api/system.stringcomparer.gethashcode?view=netstandard-2.0#system-stringcomparer-gethashcode(system-string)

**Comment by ArcturusZhang** [comment]
Hi @trrwilson this should be resolved now in the latest version of the generator
