### ISSUE TITLE
String-based-enums comparers have to be case insensitive

### ISSUE THREAD

**Issue by pakrym** [Azure/autorest.csharp#533]
To be consistent with normal enum converters.

**Comment by heaths** [comment]
When you say "normal enum converters", what do you mean? `Enum.Parse` itself is case-sensitive, which is why we chose the recommendation to be case-sensitive at https://azure.github.io/azure-sdk/dotnet_implementation.html#dotnet-enums. If you're changing the recommendation, we need to do so meaningfully and consistently.

**Comment by pakrym** [comment]
> When you say "normal enum converters", what do you mean? 

I mean generated enum converters - https://github.com/Azure/autorest.csharp/blob/feature/v3/test/TestServerProjects/body-string/Generated/Models/Colors.Serialization.cs#L24

As I've said before guidelines do not seem mandate any casing requirements they just provide a sample implementation.

This is something that is service specific but considering that code generator intends to cover as much services as possible and a lot of them send enum values in different cases we've opted for a more relaxed implementation.

**Comment by heaths** [comment]
I'm not disagreeing with why the change was made, but then we should update the guidelines to match.

**Comment by pakrym** [comment]
https://github.com/Azure/azure-sdk/pull/1251
