### ISSUE TITLE
Track2 CodeGen. RestClient need to use namespace qualifier to differentiate httpMessage in XXRestClient.cs 

### ISSUE THREAD

**Issue by allenjzhang** [Azure/autorest.csharp#762]
ResourceManager has a [HttpMessage model](https://github.com/Azure/azure-sdk-for-net/blob/ux-track2/sdk/resources/Azure.Management.Resources/src/Generated/Models/HttpMessage.cs). 

See manually worked around [code sample](https://github.com/Azure/azure-sdk-for-net/blob/4fd28513d42a860897a4869285755ccd658e57f3/sdk/resources/Azure.Management.Resources/src/Generated/ResourceLinksRestClient.cs#L50). I had to qualify the return parameter type with Core. Otherwise will generate compilation error.

**Comment by pakrym** [comment]
This one is tough, because batch invokes C# generator multiple times the generated code namespace simplification doesn't see types generated in other invocations and doesn't know not to simplify the namespace.

I've added more tests and if all code is generated in one invocation namespaces are correctly simplified: https://github.com/Azure/autorest.csharp/pull/763/files#diff-cba957c8dce5e018484195a92a34ddcbR39

We need to generate all the swaggers in one run instead of layering them one onto another.

**Comment by pakrym** [comment]
BTW, https://github.com/Azure/azure-sdk-for-net/blob/4fd28513d42a860897a4869285755ccd658e57f3/sdk/resources/Azure.Management.Resources/src/Generated/ResourcesManagementClient.cs is also wrong because it contains only last generated sdk.

**Comment by pakrym** [comment]
Solved by generating all resource swaggers in one invocation.
